apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: forgejo
    namespace: forgejo
spec:
    secretTemplates:
        - name: forgejo-admin
          stringData:
            username: ENC[AES256_GCM,data:f/f87rqc98vk2vpt4FJuCg==,iv:wrbB4je+xnDvIDgIflfgCkJ8AgllcSL74EpTWV9ptdc=,tag:9MXgqZT3P2IIRND/rYb+RQ==,type:str]
            password: ENC[AES256_GCM,data:kWObgNJ5wMiUaDKIht2ivsSQQPpC8/P3VscV4FIBxulitJvEeSKSogHxzNyLGF9V,iv:uW1pPQPFVD9Nu/Kx1JgL6h/IBf1dC9EnhBv2eIbkPnc=,tag:E/Vjffzi5ig9eSmFJJJD0g==,type:str]
        - name: forgejo-security
          stringData:
            secret-key: ENC[AES256_GCM,data:t5gUG3KbRbj3K2SDruAwrScdNEmN7Nsqhj/Uil4YkiAh88VHItz92zdvWgLY+Jble6TUUj8BSmBWWgfdrOb2Mw==,iv:GQ8sDma1nFhwoStHTLOQChX8Il5ij7pQub677txNzdc=,tag:4GUOWJ2/pIaKwylI4BqGnQ==,type:str]
            internal-token: ENC[AES256_GCM,data:PzESOxs/RWwVobVOYqPaMUcRS2ndUl+6FYP1MJfQLXJp1cOzbfzssKqQmtkr4FFwgBTquhkjniIcllcEH/04uLCo3mYBp7GrYLF/rl7MgDM1afzwrgE=,iv:/EWQEtWJm3JZVZqr8ENRQODQAib94pE46HIcVn/Evbk=,tag:nFzSWjkjoVLOZFWA+GGhAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdE5kbi9yZjQ4UGhKb1ZM
            OUp6Y2NnRWdieUpFd1JkelAzdk5zaExrMUZzCk53WnJlNmpkZm1jL2ZJclVqN3pN
            WUF1cWdvTkdIQThJeGo5bFA5Zi9iUWMKLS0tIFpPSXBTdmdKZVpqT0dqcVo5RU1P
            YmRnTGxHaHVZMy9ReDNQOUovMjY4OVEK5S7Fzpgq6Yh58eFATBa69L9gwHdJDcce
            xzDpty9IL0LAsFbTyjzNWOYYPHu/k3dN38HgM41I4hAN5EO5rESjpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T18:59:09Z"
    mac: ENC[AES256_GCM,data:m+kEcc3VM8SIMeNmwO9C+zBsL9MkwJgbzzRm4RubWd0TYZtzlcuphzIvfnP3/dTWTEpNarSL+CsYolAMJ5FiQM8Hpdcvwr//9J09RTwgrFj+v8aDuwVLk1f2qtOxq9kawXqACg62e4P20Tw/2Fl1kHRnMop3NeCiS5EGI0HwDxI=,iv:LBjPseL6A23CvcBFMnrAoSAwFYzh3gPZvdDuX9FBWug=,tag:8WbcvcQlO4BHUUuzycvXsw==,type:str]
    version: 3.13.2
