apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: ctfd-cockpit-ingest-secrets
    namespace: myrctf-monitoring
spec:
    secretTemplates:
        - name: ctfd-cockpit-ingest-auth
          stringData:
            ingest-token: ENC[AES256_GCM,data:v0qLuW36UpvCyXlUsU2x0sUTomB9rGLjtH7xHAhPnDATY/TZmMTpRRUCRB+teXHN3+PKbxnbTOavyNYrK6twdg==,iv:T4kxx6Cpj/ACUZG94mcHp87/YZn2shI09bKwWndYPYU=,tag:t+hcAeFSFi25oZhQ4/l6/w==,type:str]
            mimir-token: ENC[AES256_GCM,data:T9gQZLKEK4/MNFgORHIwW7Ra2oaT93pmaIm+mptofZ3t28Uyqgld54PVKXgjo9OsYJw11RUCFGZen1XwUs9A7A==,iv:kvxIeLN1dWqgrPhl6fEQ9g37/GNBKLZF/Uv9FwLuMwc=,tag:jH/AXsZJnHbPQa/ftbkr5w==,type:str]
            loki-token: ENC[AES256_GCM,data:hjcpzhHgObyyOx0Bplz+2fmCqwfWyx7zwdYZ1n7WxSfKRAtFk31w13v7/ckdCpp07yk93bm8ia275WaIoOr4cA==,iv:XxgnQtQkwd/JDKNaL6zYZwY+2ou75x7mNLlNNxKbwB0=,tag:/D+zgybON6YODQWJimgmrQ==,type:str]
            mimir-tenant-id: ENC[AES256_GCM,data:kQeu5N7Ud+buq6ZjlX4Dsg==,iv:GNClSfJoYSli6Mm3PHOWzwEMcmhmqkSn1xeIgFrunes=,tag:0VwIGxMoix+M4pw95RtzyA==,type:str]
            loki-tenant-id: ENC[AES256_GCM,data:7COCpBtVyTtsYPi+MfMygCM=,iv:QmHFGLwkG0BdyqKigQ++Sm5BBL/4HJPttW+gy7Lv9BA=,tag:WrCRAOp4KHMYVSM2ZcwvHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cFkxYklVSGRwRGZuREMr
            LzRFU01nZnRsZlRueXJ6aVl6dTdBLys1UEVnCnFpSHo5eDRqdUV3amR5VGxrejRU
            SW1WQVhYWDhyZExkQkJXazdCY05wSjAKLS0tIEZnL0VwQWw1QWtId0YrdjFuSnEv
            YVZiY0F0L2N1MksvZ0hGZjBSWEl2QVUKB32BXaUrYJNl7s0sboPG1MO0F8Vypatc
            d2paTg4QiEuCPEbwzNpuojhlPd4LJqeskY0Qsk2c5QDCB2Ap7TJ04Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T20:29:05Z"
    mac: ENC[AES256_GCM,data:YIxWhBEB+/rZlX6lArY3XdXy8XcktEGXOvxA4DbLkqGmsrEkIHGSqUOax/GdFBYpM0MzSaA163sCSqDRgXZ9WTApOW5rG/nx9b+hbfPIvth4NCEN6mpvlpA7TuBKAHITJBwVfM+tGDRP14fF8+NbwNVIqY9yXs6WxHnTIfhKJOU=,iv:NLg1AygrxEY0Er0b73xOSWu3jNQ0FuE9gZwH/rOFUAw=,tag:h2PckDMSqJaoEu8h89tvbg==,type:str]
    version: 3.13.2
