apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: myrctf-monitoring-secrets
    namespace: myrctf-monitoring
spec:
    secretTemplates:
        - name: myrctf-grafana-admin
          stringData:
            admin-user: ENC[AES256_GCM,data:+C9t/e0=,iv:qyFHCKDTo5vHLJ1RrVr1uMIQuJ45Uus5kEs4FsB5ofA=,tag:bp9sJrVNEh8ku6W9GTff/w==,type:str]
            admin-password: ENC[AES256_GCM,data:o+htGg+3SnCoBcoJamZAXbzgwQmLg1yzmdIYcsbBhdlEgb2QTuR5hf7DbsnVzXgFlXQlE6O4urEhzzsoxcG5Cg==,iv:w7j9LTMePEiS+Qy+BRIvoD3RYJVR+3dHLrazw0QmXsA=,tag:CPd9pt79yCbC2R0wcF+B0g==,type:str]
        - name: myrctf-grafana-oidc
          stringData:
            client_id: ENC[AES256_GCM,data:EoE61OuBzSuTxxUtuWc=,iv:IN4PWQB873yiw1cdRWvnZJvjT6nyruKKSmyZIrtWXR0=,tag:e+33oekUYifuk731cjIMog==,type:str]
            client_secret: ENC[AES256_GCM,data:gK5KqpXMEmFHDF3cTsLzZq60ACvca/tz5uJCIuSCmtnvCtzo9/36dtbQtCmrAI+iFHZp/+aac5Qb6c3cpZUYOw==,iv:v23fEHaFn5OheedJIihTsbbWm0/jwnbOmvPTdx8VKQk=,tag:mRFDnp7FI//tfWhnc+TSfQ==,type:str]
            issuer_url: ENC[AES256_GCM,data:2o16ujNlD5I0/4Y7daORd3z4Zbk=,iv:qnKist6mOwdWjFZZW0vojhTquk/ZNdk1Gs6OkW+LT1w=,tag:cQFAwaFwKBXkSfipbTRYNg==,type:str]
        - name: ctfd-cockpit-migrator-db
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:c5xV3p7gURMmFF55CSNa959PcdoX,iv:jJV5oXMjR6vmnMMZHsQqIG0+xly4fcsXfoYcQdpVEk4=,tag:HPEExDpYfeGZ3EgWkn9+YA==,type:str]
            password: ENC[AES256_GCM,data:ieWdG3CJwSxaUULxwpX6j59vZ8XH5m7ZC8DpJQu4hUQPcbnxCJWCGPfPNvFx+p24wua15oCocGU24g+dMiTtRg==,iv:Btu4bjxFxNrolpjK2AMsCANs6ZX2o7ni1zyOzyR2rWs=,tag:vORevnalc2ThcDIHl4a/hQ==,type:str]
        - name: ctfd-cockpit-ingest-db
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:d0dG52S9GvF9VBb21+Hlf88ltw==,iv:5W7z9ApY4WyGMJ2dD9QWgyWcVIuWAfA1jxYIzFlgpco=,tag:k0qrDYfDdopHqJ2K25jW5g==,type:str]
            password: ENC[AES256_GCM,data:Qvppla7+9IsouuNHqoJNyEUoALJC3xYKUrUz1Qy+6eS2zMQdnZehBWV9rDnpX4gFTzZgd6m3kfHn2ZWRFUrmHg==,iv:Ci9pRRXeJgBbB5XdShdYuDj+RlHtymnuysPZkSZb6Jg=,tag:DXH5AOxlYMM50LnC1voiWA==,type:str]
        - name: ctfd-cockpit-grafana-db
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:42evwp4mhlpaBqHdgFPj6P7JyHo=,iv:3QD3RAsAww/QDdDqwlfGr+ZTSEbTPvBa2HS7ibF1mbQ=,tag:qVat+90yJQF9UkF/Ncadzg==,type:str]
            password: ENC[AES256_GCM,data:V+/BZAkgC9UWaikvMmCrXJpSOEXr53LW0EQibER5D2b9aAz1sbpIMqTa9tlmo2seylSFqn9Pjc1Vx89HvyrOdA==,iv:OVsLCyUhCqzcRrzQPRc1zAPmdJNkxpSUvsPSxSjWjIU=,tag:himOmmEY2h8EgtaS7Q73mw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArY1lBTHFaRmE1eG5QYk9x
            SHVvUnIydlRMekZXUE9BL05UbzRhcktPQkFRClFWRVE1YXY3Z1BZUHlQQzd4Sjh6
            a1ZyT3p2UHhlQUlwSW5MRzBHZG55VzgKLS0tIFNIRjFUSmlMOXNRUzNQZ0ZzazdF
            QnBGWE1iUlhlQ3c5V05GUkVKM3hiMlkKccZHlpTJTti0pcRsQyTcbJ2R3I5xCqEz
            xM3cVRh/8FJuin16RNG4xUDxA7u9OSUcaGeNRihiGRbmciAeKok/2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T19:53:19Z"
    mac: ENC[AES256_GCM,data:p8AHyqnvS+c8uMD+bFWLb8/NUESxe9E7+mIi6WGCbCcyVImkMo1zmU4GF4vyiEmkv4bWuSMnM+7Y3KKhQegihFfkcgHSrOJGr/lCnYw+p3p5tIntMRB2caOD5evqoBX1mI5QTcF4liyhSCSGpcBC44+4sQInXGeeH32TEJ6P4F0=,iv:1LV3p7UBSLU+aknIBMALS1F6B2oH8fbQXXZpkk83jJU=,tag:tE168zz/6SR7tBrO28dAEA==,type:str]
    version: 3.13.2
