apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflared
    namespace: cloudflare-tunnel
spec:
    secretTemplates:
        - name: cloudflared-token
          stringData:
            token: ENC[AES256_GCM,data:1Vax3VCEV3JRNFx3KHvje5MXvcmoWhyX0CUlorOfuluDxiMjVey1cp1KXd/UTJ+T2EBbpxaB6pE0iwXYtghYa1Q8Aq9cRMxVQ/7VKgbuaeY8or3RzB4jQvx8JsKroId9h8sqvMvEGEkLOP9vx7XiQfrWJfnW4ioJvvbCicwE+7j751ON8O6009l7O+ISJuEpR8SBH65IFvhmAGGymq0VoQtG+np19Fe3k3KTtOrcOMhyze90JOEXUe0WjP/2mufhQjfSKH+LT/dY8z6gSNsT+oHaAmCVXTK7cAkmE7Cs7AHl13Pp9P2ODP52C28HdEqE,iv:oinJdeYJrMO/eJyeMD4LBQk4mZ443QTrLptJpT0DSMo=,tag:R+CjGIXhMo/q5GhGSlWGGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvR2hRRUhOS1FsbThWbW1r
            TzNrbGp0MWZZRVhsTCtkS0R1WnJvclNtRFZrCjhCZ0ZGQ3U5TVA3WENUUlJWRW5T
            Q3cyNjVzaEVOcXZGUTNjaU0wMmo4cE0KLS0tIFJFcGRtVE53V2RuZThyYzZyYis5
            NWoyMnNiMU9BQ0V4RHdqVFlFdVMwdUUKmpzeB+Rej1C94BQl1Apq1NYHgPfVm+Ix
            2z1Lax/1sSYqtBnQfdgRrEehhZNO83/EfjwzaNM0QrcLfAI2XyQtjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T19:33:59Z"
    mac: ENC[AES256_GCM,data:vWkZipTZDCW2bGl2SLFMJWQNk1lu177XJyYMDHK7DN2ucsOgozxxaUGujFbZKU4NzPMniUsmMGtZYYHJa/ATxHbdMMmkidCUCQuU0A43d6lu46JEXVR4PoRoliOH1oIb385HTrIlR28uFT3+iFQroHv/tHN/FshQDleye8xQmkQ=,iv:ZofzgxeDx/2uGuol7ynbZd3GUylsLUjaxGOVSE3rK/Q=,tag:5R5SNzKJ0Rr2AhhKZuAxig==,type:str]
    version: 3.13.2
