creation_rules:
  - path_regex: secrets/.*\.yaml$
    age: age1fh2yetxtj5apky38q4qek4qcd69pklgpqe8etlvxc047znkcwflsfa798z
  - path_regex: \.sops\.yaml$
    age: age1fh2yetxtj5apky38q4qek4qcd69pklgpqe8etlvxc047znkcwflsfa798z
