# creation rules are evaluated sequentially, the first match wins
creation_rules:
    # upon creation of a file that matches the pattern *.sops.yaml,
    # - path_regex: secrets/.*\.yaml$
    - path_regex: .*\.yaml$
      encrypted_regex: ^(.*)$
      age: 'age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz'
