apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-admin
    namespace: monitoring
spec:
    secretTemplates:
        - name: grafana
          type: Opaque
          data:
            admin-password: ENC[AES256_GCM,data:WmibDXxPz23E8aTpTSIlR8tU/OdDNbU+5kc131uFQEfMdeeiiR286VV68LX+eUE5GPoKC4BkEgv51kZjBOrnFini9fwsbUD1,iv:flHld61Vu27AqltFLPOVSvi6C9D4EMPTTn8DuCgOD+Q=,tag:RKNWiMuD9o3+ieZMC/Ly0A==,type:str]
            admin-user: ENC[AES256_GCM,data:11Rgl5+rbh0=,iv:APwOQsz/LhLY2WuvLbPno+cRwvz8mlazwMnLSmBZYbk=,tag:cENuB90zWcyB79d3F3ePBw==,type:str]
            ldap-toml: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VHNXTzRTWVpNZGdWa1lq
            bnJJbnVGUjVOZnlaVkF6UllIT0lhZDNuNFU0CnNudDZpTi8xRFRja0VvTEhnejZo
            eG1zV2d6WG1HeVJBTU1ldjBnZktHSHMKLS0tIGw0dDJrMUdZb0lhTDhyREJHWkJ6
            R1NXaG50V2JtNEFMbzJZMGxXaDc4ZzAKKF5pTccNCL4BEvrvsFmaqKWBtoMEgWTN
            m6MUeBB59sadn/2MsUo/sJwv3cUGWlkdMX4jlfTOBn2t6BxjQU4BdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T18:59:44Z"
    mac: ENC[AES256_GCM,data:ZKzItf+B3W8ZcMd3mK1gJsM4V9SaLIPVi97ss5WsR3JHoXvQ/W7pLHArBko7eM8zCOcfBnRz2h5iI6E3bLyK0PcbU6g93ohmcDDW7Baewebtwq/kZTqoE8VmdQAGZgAyn9+PEPw7vTCmquCUVjgYy7Jw2bvKtvpMzSqiWz3QCic=,iv:FSa9L9cx0mINaBfQUJCy4oFLlz4NllOMtmNSMeJ9ce4=,tag:BA74O2rR99/ZE9UJk+J07A==,type:str]
    version: 3.13.2
