apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: t3-oauth2-cookie
    namespace: t3
spec:
    secretTemplates:
        # Dedicated 32-byte AES cookie key for the T3 oauth2-proxy release.
        - name: t3-oauth2-cookie
          stringData:
            cookie-secret: ENC[AES256_GCM,data:QW59vbmNyMQhFeI4Xir1XeYjGoECqRObPtFoPCoEVGw=,iv:AV7BYQgwZq12vA5EEmptFcBnVgnMTR9/Pp/HAnWDiMA=,tag:QvKHxkPR9cHp6HZgusE2hw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORWszak90UE9Bbzg1cFlX
            dXBRQWlRT0Y0TitxeUt6NXI1Ly9UT0x1a25FCmdKd2xyQWRnRmZ0d29lcmFtVkU1
            ay9pUm1mdkZHRFJYMk5weGRXa2dvTVEKLS0tIHNqNVhSSlcvZTVuRzZqclhNV01r
            am1Qc1pVeDRqWUp5VzkrUG1PdDhERjgK7TP2pnBcs/7BsaRZ4JavB6vFYw/3n/lB
            mBkgCHOuzXcmc9dAej/5hUouJu4IAmDbfqGzKNTPWtZssRzxMfqu5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
    encrypted_regex: ^stringData$
    lastmodified: "2026-07-10T18:35:08Z"
    mac: ENC[AES256_GCM,data:BYmk6kMuSQYg1u6MkiXNoj34m89DnyhJFK3VolBc5VcYUT5Sn1gE/+GbdT7ujM1N0YhKs8Y4w0cbW5ckP0pU15e5ixZg8H+dlUznZcCQnzRRu3dBphEkO1Du5RRyyaqNSPkZcsiCryB7R2Lx7u3xW0fUOdZxY2yde7pUZgdgWCk=,iv:TAE6atyhsjCTEfgjY0FVQOOVmRdtVTZ7gH6zxxW4kHc=,tag:894b9tts/RNK3iwKbSdqCw==,type:str]
    version: 3.13.1
