apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: navidrome-oauth2-cookie
    namespace: navidrome
spec:
    secretTemplates:
        - name: navidrome-oauth2-cookie
          stringData:
            cookie-secret: ENC[AES256_GCM,data:dSaFP1fRLScDBqokIbasmo9K3ddbYYOLhtx4w2nanqA=,iv:zBCERIJW7UsE1CviyQrNLS4aVsLVfX13iIzZ4kXR7yc=,tag:e3cPvyZwrgOVynfK1AwWbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSjBabHFDWnV4ZUZ3dTBB
            YWJhbE81QWlHeStLVEY1bDJVemQrVU4yYkRRClFSajNrRTFZMWYyZzd6TjM5SlFL
            UEFIdHlyUXJiSlFmbS9lS2FZaVVYQmsKLS0tIFRTMkNHdnE5dGFETEFWSm05dVgv
            QitmNVAzRHhmZ0xUK1FnV1E2YkFtVFUKNRPXf28j7iTGS7qw1He+Y1NfjLs3EaDV
            w3VnYsR5pv3TQgxg9E9/8e9Srofltlbfv0mTNWjEqkbpiyMM+MHFGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T10:33:04Z"
    mac: ENC[AES256_GCM,data:CCKqT70ZyboZJyE+ibLbyx41QRj4yDuOqn3PqPdqHNEfC0iMis+nLlzVzAMz4os9BhT6/Fgve7lOPCUObk8k8vEjXGWwrHmDCcabFd/LHsHr2BAGc+wM2x2bIOdvG+5nVmiZP7vcfqI7qTKreByk6dFqpc2p2cYUkV2wT2aaLew=,iv:M8rqIgZQIZTNjkMwr5O1/i5PJnjQGYp4p67AL1kEN0w=,tag:fVTORP84oJpbbk4HZwF0kg==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
