apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-dex-authentik
    namespace: argocd
spec:
    secretTemplates:
        - name: argocd-dex-authentik
          stringData:
            client_secret: ENC[AES256_GCM,data:M+y6s6hRtiuGThrYgJsMhETMQemc2S5cou1hlk5fUQJkPssOp3xjs/2mp9YjToUY1BewCGFMc4ffOAewiTOatA==,iv:hS76QKICC8OuxFFhE//F/o/4N6pRCpIk7UShhz4BtLI=,tag:l5Bc7SuCQlQUarRZM4XKSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MUs2dUNHbmtNbXIvSmQ5
            dWx2SEgyUDVudkY2V0JUdmcyMHZCYklRWWxNCitkdnFkV2N3Q0FYMkQ1Q1lqZ1U3
            ejQ3NVJKTDZJY2VGSmcvalBYcEpUTU0KLS0tIDhHbm90amRTRGcrNmNDWG45dWln
            Y2Y4YTIrWjhFTG5pdmRJOVRheityYmcKTEqON2X6Zo8WtLvt2RU/7jOvCjJin1Y4
            97cJjlvnGzYlKlpgqcUC8G41CsMculMCFkeo9x0fXIFiYYpmoX341w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T19:38:41Z"
    mac: ENC[AES256_GCM,data:MOAVz1LTLDT6tv1O0M+lRtScH75gZoIj8a8y1bBYXW86y18wWTFButJk4hU2pQDlTIVW7gX0c1dHb51hniYwCRw8xUNl0ydbnJTUQr1ceIddbuud/Pj0LafUGFcpE2Absh8QOoKnF0iKKaXbQ9IMWj3MqCxU7Sy7RkQ/5TgTCbs=,iv:o3pwQqks5ftFC0Gg6M+M+P/F9GTkIW9gTS5qEhTLQe4=,tag:K/22WQiDCDfdpUGPjrI0XQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
