apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: bookinfo-db
    namespace: bookinfo
spec:
    secretTemplates:
        - name: bookinfo-db
          stringData:
            DB_PASSWORD: ENC[AES256_GCM,data:qF4mu9wkjkMilU6auczACcmKAMtqcvy468nuZzn6aqJXcjegZRHRzwI4x4WwMnBp,iv:KGm7t5CXQfzPfCvNPJgN4V4OaumHywBAJyhf1tXEJno=,tag:55HPXxEM7oSlpRk9WzMF9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHV3ZFNzFUSmJ5bzZkb2lz
            U1ZIbk0xTnd6MjZzNVhGdG9RdFpmdDdsYXpNCjRRTURQYmNDVzdsN2FrekhKcUZh
            RkU0dHp3MExJcjMwWnJXTXREOW5odWMKLS0tIFBhR2sweUI1VFVLTXJTNm5adHZy
            TVBUMlB4VWNxQnppNVVybVlROVZWQ3cKjRdWTk/Zk7J1+oe2zx8caHS8ZK+IxPUE
            Ut+8GNFQIZxPeaJIGVo2RmGYBv76WQutYrCHWQgcUoZ4OBcwc5HH6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T21:58:23Z"
    mac: ENC[AES256_GCM,data:CM3tC/wtLo/m23qEllpWOEfUdDPvQrk2GPVsCQE4swo2ojoONdhQfajDnIRNDB3xdIEfraMO+Nti8XClBHBrI198vCAw1EsmVsT9G0KVfr2/Vu3R6V5FYipdXKnE0brHv/7tHsr5ntLejSQxFjtTajBXc2gXxhqdDrT9F5aXSbo=,iv:L+SlLiSjdD7cb+kTPCa0+Fljn2KfjYEskibsI4kAN/o=,tag:uZzUJddZs7eurefXfwpKgQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
