apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: crossview-secrets
    namespace: crossview
spec:
    secretTemplates:
        - name: crossview-secrets
          stringData:
            dbpassword: ENC[AES256_GCM,data:IjxPPdbMun1Ln/Tft7ycG5bnZTUuoJDedYqecq92dO7Pphfmwq7SLwfWe8XDecEZ,iv:ikLEB1y/u3d6zi8CERddnzeluhA45Xm3eC4sBisrW3A=,tag:59tOKLiJjf5MUdkAPHH3hA==,type:str]
            sessionsecret: ENC[AES256_GCM,data:QA72zrnKD5EygDvAMevsc5P3L1cAzLxZNQHaTugwJxTv2tdMAYfplzt5bHIdPh4+KBX6jfJGAl+rgQsvjwqRsA==,iv:XU999yasYlJCxMCwUMwE+v8WN9w05AB4ND884I9FJ88=,tag:i1vVFOGyVNcPMx565QIYnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTWt0NTJEZ01JcThXVm9h
            RVE0ZG5FMlloUlg4bWdiaUpoMnRhRlE5RTF3CmtZUWJMRjBhTUIzdVBwRG5DSmRm
            YUlWNWFmN2lFQnFMZ09wbGRSVWxwd2sKLS0tICtUVjk1MkhkOVZrV0JwK0Vsc0I4
            QXBPSmJIRGNpczJiMzZIV0J1S3BLbG8Kzuk314YZNdVb/QtrTFiIg1Ge5u9DqZd9
            nQ6vV9tFhl/PPFjLzIgoSmzdIUapNrL7cu9iIDmh7YmaXlduxyi10Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T05:30:19Z"
    mac: ENC[AES256_GCM,data:u0t/btQJvKmphgrx8NcL3ms/fZmdByFRi66s6RrYNK7H178Q16kHRJc5qdqr+1rmREVEbYdlE4fCJ370kvHPYrNW7y0nmNH7m/N+v+WCZnLsZEIZxzobekRDdhVfWq/dctgvuVQACTnDJ8WpolgRS1IoXGzW0Px1eFP3Mk4wVz4=,iv:yvqYL1GtIjtoEP+zkxw5a30ZzxnBvFv2Pss/M49BhS4=,tag:pcaQz8TbLUX0NrjUU0Hfew==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.0
