apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: crossview-oauth2-cookie
    namespace: crossview
spec:
    secretTemplates:
        - name: crossview-oauth2-cookie
          stringData:
            cookie-secret: ENC[AES256_GCM,data:k4bSNxMDTR6EwPSEdnaUbpkbsZRkW/cE7HV7JBcEG3I=,iv:ub9B5oSAAPlUMNA4njgqEKFqrk42xFfyZo7mGgjVTEM=,tag:tp21mQWuvnYXOABa5QUVRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSGRNeitBYnNPS2pCcFZV
            bEhyQUZKOC9WbzgzVnlHdG1HZXJwOENYYXkwCjBaU0VJM2NZSnFHYVR3Nk5WdE9q
            b2xhN0NCc1ZxRGxjS3NpODBlUFZMTzQKLS0tIFh5cGE4Q3d3ejhsOFo0TGlkL1hB
            UUh0Y0FBalExWVBXTXBWMUYvb2FwYVEKqe0Ux2FLc39xpJiQmpHGOCS8LXJe0vSV
            ONJ/Y7w/aUM2FhOcDIOMh0bK2OrQ4fGl74Yqxdf+6U02wqDLySyMsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T05:29:51Z"
    mac: ENC[AES256_GCM,data:11zc48e8+oFQaZXmWNAtKtOg4RBbP2C3HbrVXdcMqieytvHSIxDtMP2uoW1AcNOvFRWlotci+ujpotQoQStyoX1KC3VCJj9kBzHJrw/2F5hRpyb6mR03fsW11jPkLLOniCHXy/OaLNRkL2jc3O22BMGyDr7YUZg17P28VdcL/2I=,iv:TNle2A9RjJkej+pSOq3S95oBY1VTDhQUY5XkhCqa5ug=,tag:A3FhL2bdju1qmACh4zhRng==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.0
