apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: home-root-ca
    namespace: cert-manager
spec:
    secretTemplates:
        - name: home-root-ca
          type: kubernetes.io/tls
          stringData:
            tls.crt: ENC[AES256_GCM,data:neCR2GrYbnaEZmFJjEH2M0nAIIPoJCI9lVdgx3fyA0Pw2DUKw53RaMkfeenlx3mCNQn1P0sslatDkvo+8LcnYVRglJ/CBQX2VksIQCc/v8kpOcWuAW74EecHX8AipDZymAdTpLD1sG4f2EmTgoF5eqiO2fm62c5eBrc8uzy4IoiuyEbVVVDKu9uMAp3NmUVxoJ30WniCrOaV7Vxdoa2PP7fySO8jsIWsJcK65x/72kitszgYzwro057PLkiGL6XFo8uHbOeSFMgiqjcl9yAntGoIcCeJ0p7W14w/oNfo+3h/CM4ti2L8NDf0CcVA/Kn85AwhiMFeG/rHQEnqiZpijSCI+dmdwcVs8mUFuolL/vtDZ4+Drva/C1X8HwAiYFvpDc0wU1jYkrU8VH19E9Ty23uY4Uu32h82iDwvuV65LKVRohVtKkKAKQ98nB6xtaXN4LJyT8ZO1kwqh21HVNwezPUrl7GOFOVSE4HcSU0TmK57wOlM+z6zze/FC7L2Thj4/bF99iGaf5FFfp3zcqGQonQemiAnWYFr8SULCGDfcVaYsg5XiY6NL8Ds1uR2zFvyjVGwBuRs4UmERIwD1sSHPMMf9JGPGa+lSEueIvMumxjek/liSyxgyU+5D98QsDOGO031gsXQPepDtqSXMaC68N634vFM1UKFRHx8oivlrXA9NUYtH26v48BL/iLcEksw3vQo3/Ku0XRNFZZyvgtev9x7TYbyFKbs7fsXX+upBdlB9xW3uEFhcHz1Rg4s1SgqpCMrRxvWdbR/65W5kE5ns2JjQ/j3MItak17Pq84RKKiSdPwa0gf/FB8qBuWU/2fdZziz2qYoFUpWD944l8MjaJ57vU+gj7k=,iv:10Dp0XRB8Ld0Zs2EpOd2zHIi0Eq/o0cWOXA+LVerFJY=,tag:mylap3F9LdQfT+ZZIPbveQ==,type:str]
            tls.key: ENC[AES256_GCM,data:h/o3pRF6wl+ZJWb9wJZRBAGz24y/5jZP8Y8jrvqJR2WgJXdotfc6+I0lmlvL3pSBADl2D1/7ihKFeHLzp0TwT0UCr0hCbQoNK0zX2G/40QYJslzhQw7I8mg5xFZP+X+ttZ6rDj5iZgCrWYeA5v+ctmbummtI/slDjQBYreUzJBP6nZ8hb+4uRjNTQpCyZdCcgGzD1gW2TZbDElU9DYPXKj5/dqdWcHfUiz/Zw0SoT9BGE7ReLWxMvBgfChzIQ8DBtzj/MTUTelDoobaHyYkz1Mu4PNENDNI81wEfovJKKvk3H4fUkvfsx95frcKMVu21nVg4rjZoOmUFx/Ko0Q+3f37uC03niYbDvp91oWkTkOunFTck7Z/4CHFJUtEX1+M=,iv:A2zhgHnJ6bR8cTqLwnAhnpYIGar1WyaZ1MUg/E0DVD0=,tag:j6Rw/YKF1hbLwVWQOrhehw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fh2yetxtj5apky38q4qek4qcd69pklgpqe8etlvxc047znkcwflsfa798z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMW5XY1FTMHlLVTgzZC85
            Wmc2K3hZOFVBbkFrS1ZmYWJRaU9SeVF2S2c0Cm45TTZhczYyU3dmdkVlOGxXSFNS
            THhObE1kbEE0WWZhdlZ2aE9mV3YvbEEKLS0tIEt6V1N3cjFEUjdEd3JqN0FKNmNk
            WWlHNVZuMlRtUnB2cjNFZGVNWExOTVkKCCbB/OI73zi5ARkV0KAhx2fFWkDvOgJV
            f4bswJYZgtG0lYx5gvk1DC+IDoxdX8pCHPmdFnKMqaOd+iv2GzqVqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T22:23:41Z"
    mac: ENC[AES256_GCM,data:lYuig0mFtckpzcLLdSDnj8d1wUMdX6NnbyeQkpdnqoCAxDMt4YjbBurSYvLUw1rTGdDaJytEEMmEPAfaLINb/k47KnC0xYF3j+nR7IaOZmzXY5eqOkb73/BrYLqpFdOdPe4GH5X10G7mTQPHQrbQJxsK3C1iQITfcBCRclKmquI=,iv:qcGROD5NgBR8dJNdbwUcsuwZtJRgghtcfdZWZL0A5WA=,tag:/LLA1I/Ew9DaysehnuFBnw==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
