apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homepage-admin-credentials
    namespace: homepage-admin
spec:
    secretTemplates:
        - name: homepage-admin-credentials
          stringData:
            #ENC[AES256_GCM,data:pzyJTQcc6IiI8rgDENlsN5Op3ikDCm9n6zBKWY316W+gQbdpKv2W6yIeK9Yj9OQpyqjTr99mlyrXPy+R7pip1uTcqrDs,iv:MG3K3MY7+lYpGzYQt1hltfnJQ1ky5C7+V/9n/PGtHco=,tag:ur8F9OdeHJpq4qEXE53Qfg==,type:comment]
            #ENC[AES256_GCM,data:g89gmuemNZCo7dEwUhaEwTnav2tzMgJa/wLtMZ0XoGnZz4w/qhJcJSHPAPt+A/eKdI0uL09GMz6w4xFXo9M5C7k=,iv:FXUfkIzILM7wRGbhwKJwt2DzT0c3LU/p7PVL5RBPbWc=,tag:QYRDOjGaj4sxiEfAlzUhJA==,type:comment]
            #ENC[AES256_GCM,data:1LNzqW0IXK365JmZ4ws6SagbpKkAFp1Ybtj+8J7gKIjrlpIE6YweSsjQ39divYa2YaQEjS9aXrTH9jjOoSph2A==,iv:Mxtrj4ouMukfJjRxjKZixz/Jkc9V9oZFBIzUBTTecEw=,tag:MKkeQFUURWLJW8P+FpM+KQ==,type:comment]
            #ENC[AES256_GCM,data:rYb148vifpJs9DkNoJNfTITNUoUokxUN+W04R1ye/kwQ2wEJPT4c0xDb2Qa0blpsLCO5Y1eQyNFNmW4GJiiGV1g=,iv:jI2SFcglkKOXf0HthZNt1k5kdO2/0h8PkTMF3X9UqaM=,tag:N6uipcANmuycXXQq/Yl1JQ==,type:comment]
            #ENC[AES256_GCM,data:Hy344Y5HpgZzhYXOt1/Pd6nxWmtIFqaJ1zIxcPhdb0rkCYlX+A==,iv:0+hbogE8reDblJKEy/P1VQ5pUKNOhXo58o38J4Nh/f4=,tag:vg637vvb0RXf6iicTPIr6g==,type:comment]
            #
            #ENC[AES256_GCM,data:QId3AneYjd0GCQ+GuLPYNaCu+PnTNCpJ+/hVIs/sBZPaHyKom9DK5qi2qgR7TbkKeFA4EqOHOXolAEFyN/1KmF2Q,iv:5IVwZL2uCo6B+2QDrlmKvnw4jXXRLYEvq/LQlLg2Kvc=,tag:77W0ZfjtxMxKI2CRJ0q2Mg==,type:comment]
            #ENC[AES256_GCM,data:KbO5Y+7rtIQiRHIw4p0BvRECUKj2u9uhee5DoyIXEABg0d96bYQDjklOCwnYyF3ZYEr57femP8Ey9akuna1Eow==,iv:7JMVyOecuW6TA/9l8QDoML63pVgCDtq1sZpTxPy5jUc=,tag:PMP8aJSa64e6OkqGUfJeQQ==,type:comment]
            #ENC[AES256_GCM,data:lh1/yM1b8KaZ7ZZ65s0q40+0EZ0UDK74tGfISLnjyNT6s1wqLg4ncP02ohwvO5Yko44ftc8PQ+a4R0V+u8F7,iv:FI/HDYs021W67FYD6VmAGfgy79yQ4SzGKYydBsGXyjE=,tag:cHTbJiNLGS9Qx/DLC1geFQ==,type:comment]
            #ENC[AES256_GCM,data:mz+Aj9iDmEAcPdjmJdC/tLgXFpvW0jJY7upWYH4u5UAYIFBiaucN9vdudPNXiehitAIuSnPTnYXrF9fhJ11y,iv:DKeCGxPH/bXpUl9DwnRyNPl1XgYiVYcsekMwYbR6jUA=,tag:30lDQ9OEeErPHB25JSufRg==,type:comment]
            HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:4QDLAcU=,iv:ShqPXAAUk9Y3GrpsbHbbMQfhWXcVD4+SrMlQTdLOuWc=,tag:dpSRbRsiBqmEkyhrw2cHSg==,type:str]
            HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:HPxTidcXJplRfpyxn2UKZtsHsrdbFQHojsImpGvQO1V/+BuVLPNtUA==,iv:HzqaAhQ9TihI/sYaHxR/4tPisaBhSodf2bIP0llsozs=,tag:/yZXEbnqnKoevsoPkgBB4A==,type:str]
            #ENC[AES256_GCM,data:kCYIHRIgJbTNjWzloQ5lFPBw3xLwd5oBeZpJsTJyDQjFNRQa9YGr11CAW/yotySz2YFrsAkol3Ffd0YjI5Sw2Q==,iv:SVRrzYEWMz9ufO07gFiQzGfFztfSbdlhQDnR9eWGcKk=,tag:0OIeYv2hHnUc7l6FUYzbIQ==,type:comment]
            #ENC[AES256_GCM,data:tXem5MoQfuxAbQvQEbOjlg9+KhX1j04LtvKqvS96I5jgEfOEvXrB/sGal9+Mq8NbeRmBGorqDWHEE/mMxHCftE+WIw==,iv:+NWNem7dCan5JXiLv6q28i3baPlJQWZrQR+maHp1mdU=,tag:3BVNOsQHmVB4ZniwE6mpNQ==,type:comment]
            #ENC[AES256_GCM,data:wRvIBXppiSyFFbKjredXoWHbKoBJ3w8+AvU4YofuPQIpZEyAsBjQW5LNrSuTJdKM+HPUiQv7tw==,iv:dmxevIvrSg6ZYuWeZjE5/AM40ZNzonYXTvCjwGo/yW4=,tag:AD4L+9aJzvim26dDsDGe1Q==,type:comment]
            #ENC[AES256_GCM,data:bA0EzKCMce+avyLcl+qprS723EF5Sw+0EJg9n8CXbGIhpnfPNle0AZ51CxtV4aUOGSjOmAqbhGAU1klVMDIqcfg=,iv:1ThtI26iJuGwyKWQG9cgjGamTfKt1alHS3heXqEy0wI=,tag:GZjiaEz3UZggcr+SLNjEOg==,type:comment]
            #ENC[AES256_GCM,data:D12h8nDy50/lUnwIyzu+oUooVPsFvNU/ZPyXFcke0i+0VJhr/bVsFqL17j6nFj3Y49aVSzzxfE2bpeCxGpZe/g==,iv:hM3HQAgV+Y02zHI8E71YrNT95V6cBnLI0n8wVPPn2CI=,tag:ujlJGidyNobz9Ls6aA7PdA==,type:comment]
            HOMEPAGE_VAR_ARGOCD_TOKEN: ENC[AES256_GCM,data:R/yNT5HsbVjiRGehmT8AdxGmh2ijPlbUry4=,iv:HMMNln7H2U9wK8JfQ9zEjBZWB+TxPBDONQnVma3Evgc=,tag:Rl6VLMa768ha+0HRz9lc2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYUNDa0NWUHdEN21HN0Fp
            dW54cjFGSGZPQVJmcFJXaC9JNUVPU0hGa1IwCkx6R0RXSkhheVlBSTBEWS95QXRH
            UDNOTTlkTlkyL1crWFZsMFJxV0EybDgKLS0tIGRCKzNIUDl4MHZLNEdkUFZaV2Nk
            dWtsNlp1anBiNXVLd2gwUFJVNU9OTlEK2RedbmVJcAHn50uwJjQ+ZWzNDc82SQKK
            +wlR1NOV7BrKTxXqfikJYhP7ue6pmUOJubuX3TfwvprNC3sPFtqwGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T21:15:54Z"
    mac: ENC[AES256_GCM,data:jT9+bHkoapxB6YXTGlAAb0BJ2Niy1SUiGM0XUiaG6qvO2bXhbbwY652Sf6AfB7+Ts+/h/me50bhI8RUEpKNs2vhc3D0SCUVmw5SN/WKw+WpsaYk72lm/BtILbV44JSbk70OGvkWo6lPzYbOwY6Kjdg3gz0gkpWk983VVfOzX5jQ=,iv:NbjVkkLQCO1Xg5D6IDYQCAyJl2LdrppGRtmR2Ro+ufo=,tag:dmGwuHe34abxbx0cR+Wv5w==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
