apiVersion: ENC[AES256_GCM,data:zMa6F6kaKlu0kw8cG+xZvUlpjuoDzV2xW9ws,iv:oRXYScglb5GS5/Zr+2YlYRsI1aopUYa35NhVbVHChYY=,tag:m7RshQ09h2vIUTh2YyCcKw==,type:str]
kind: ENC[AES256_GCM,data:kATJ0ghkr6ROlA==,iv:iDpnyx5Iu+qYVqgqeFu4YvhxB167yewZT518duQB+z0=,tag:wKxdX2wM32K9TXhkHGTN7A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:I/qUn0JdIxMI3FwT,iv:SkQqu8F0u99s7uCpzJdZNCdBvfJKx6bjbwuZSl6bdCY=,tag:/iAeN9BKhwujo5oWm53NWA==,type:str]
    namespace: ENC[AES256_GCM,data:5a4yk/vTTUpe3zDp,iv:0ZO/NoOKTsFdoi/39KeORWUrr57wNOxlOcPe5B7tdoM=,tag:5u7ED7/R48mvwfJseb9QhA==,type:str]
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:QZYoa7qkRcggb/HU,iv:qKS9zx/3AiQqy8A5tCaUdSc/iMiNOKgflWcVFZaveek=,tag:qSH/h/x1eWc2jJoqQreGEA==,type:str]
          type: ENC[AES256_GCM,data:kRdemKmlbBCI0D9vqjDrCmc=,iv:KD3uG+FR9H7tYsk5HpMtUbIl96ZzkVcOSAZQHpX34WA=,tag:Pd9pWo7YOgXOrzIjGYakiA==,type:str]
          stringData:
            tls.crt: ENC[AES256_GCM,data:Jwu0eoB1BO5WuLz+7sbYemVHV6Orhx8a53mXS800qyob87z39L79VofGM6hIv2ivazveTCIv+/doXqvotNOYQ0qWmJQyUVBU8wK8upBrmAy/4bJQ2NjwBXIW0rq4/N8PoQP/4nDdvUffvRKV9K5h3IZjg3TXLtvHBa/lRlMz6Uot2CjlN4FHDWyqoTCrbfTUdaheNQLQSJjTQNhr/xwT2mlL5/jVU0RbqQ/CbPDT1HnUlKUljSTWzpY7K3GEsaKMxbEyNohkdD31fKJJq3rOvE0n0hZHf6YGceYBL5SVJ17IGfWTzJgeSf9VQfGtH2rHDsKtywcc2W5Z8AFSgIzA0Z8KhM2Hn7uYWEWcBsPl7W8s+qq865pIa8Jb2fjGc9KtHyJxinRLjOxSdYP0qSBzjlSkZwzdf5fu2JeavZazIGPfFuLfledMq12XzcIviqOu6ODWf9KiQpn9W/mUuedGQmOM3RMzeMNuzIRAkv0e1+xUEnIfxKMPs1ahiBom/WCpn3ynu/He6VC5lpSOvPEOUY3tlV0KFus3P21ZBtRZ9BiVqA5WQ4p8Qq1SAHVgCNf8bns52gB7QIp7leSBnCROZaBljDRIG0EeyPUAKm4YcynqYuvXWoDNSLy1f2nQFwriWB7diMkWmiKwpN2qK7lZ+bIrW3f0xAIrODqToHbAVeyMaGl6Nj0AK4pmfLg1GApVMhNCKVXxViUNkh5mYSQFL5erCuNJNMk2ackRs3teeIZ4doEVNQEB9/pQ7Ll6ivUeWoFnCnfXc9xnzpJb5Mi+B4OyfOtvdxyABt/3bWGn+OfXxj/Wn1dgmDYrEJTaBo8oEUhOf2Dz4SurVBQyDZ/YJLofau80v6lM,iv:FzPX/WySrdcw+C6MQ8/8XZES9EL5cXs878kEly41wRY=,tag:qxn/6Gd58TSrqSvN2s4wHw==,type:str]
            tls.key: ENC[AES256_GCM,data:cOP951ZH4GWYLfoU9QyLbmrgCk+b/UwnoWWsZduVZcXUxHo/XitxXUVrm6NfX69z0+ZLVOZtVXDz2OTEr1fVr8wZBzrKlcRX8E8s7cSh7sthPgyeCeMnp13a2SFITdHOWxjuHPUnskV7d3V/0cUu8pg+kU4+fWv7O3XJML/H7XZxJZIPKM/5Jc/X0CUfuPPkDH9COPcD//foyEUch1M4myPn430iRGXlAC1ee8mQNykwfEnaNlc8Ym4E45ERJr7sogwyFLO4LkfPLJpVtQ0ICWRhEPtJGiZsWitkNS/JV1C840ldvYh66bZQksL3uuM6J5ynApE2eO3Oy5CrpMm1UocQjryrrZ5FHxMcSCZx2qyct8PL2w6oIzefpAOmneXF,iv:vqu7frxQWknulTxDFJ1bx42f3jbwa1HViIGZ2m6T0zg=,tag:PKYWrteNBKdMveblLmzhBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fh2yetxtj5apky38q4qek4qcd69pklgpqe8etlvxc047znkcwflsfa798z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZTIvNkRBMWhQb3VYN3lN
            ZVdoSVh2QVd4WUZsekVSNk5pUGVZL2FFVERvClhyMTdPc3NFZ3g2dnJTZGh5Mi9G
            WFF0RmwzY2I4blNkRUlOOG9pZm9nZ2MKLS0tIDFnVkt6SDVEbk8waVZQemxpc3NR
            UWdqekRUUnhnYlNpQUV2amE4dEpSNHMKqCmbVqO/Eym8jzkzjCDrdsPaBVLIyOUU
            QopQ9ggLRy7wZANQgXSqYc7UKKUZlBnCrn8Q0LfRHQdvr23sqdGagg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T22:08:29Z"
    mac: ENC[AES256_GCM,data:1KCkq50J7eML+kMUNECHwxEd3vMayj/YzHQfuUgA52MluQoPodQU3LXPe0BuWrJAUqwA/AeyHd12gmnSfZKKAvhIOVo+L82ZfbyjybuaDz2i+75E1/mTwOS5fIWkXF0vTNT1tgqjkdIXtJ02nWS3KUWs7/qTQn0Bx9cmoQV7uTA=,iv:3jVd/F3Qa7Udy9bixsNhCrjE/En0B/KdX2LsIMqKdCI=,tag:v/jpWs+R00Sm8wrkGEirVw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
