apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: n8n-secrets
    namespace: n8n
spec:
    secretTemplates:
        - name: n8n-secrets
          stringData:
            oauth2-cookie-secret: ENC[AES256_GCM,data:elyCxRfKBkMfLQboyRV87BOOvkCYx1GQBsUAXYV8Mse5vUScumACVzAQfbE=,iv:1/LJuNrpH7/n/ELLGfeks8RQeThY9KU7eT4ClTPrSbY=,tag:sOJyAz5SLxr3ZLJiQIbT3g==,type:str]
            encryption-key: ENC[AES256_GCM,data:CKVNt7T/QwipSgPsJ+VH7QafZPJUO19aRrH5GMNRqynJpLAsw+bmdbe4lA==,iv:s0MXjMP0XlFO1/EbYTcTs1G6T8fOINd01lhYTMIUtN8=,tag:iBzy5IpvuseACuLEeG/DnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQW9xdUoyQnU0WGRrL0x6
            ZVVNYzMvbG9VN0s1K00vSHpxN3NzZ0hzcGlNCk9QSkFGeFE0b1U0S2Vyc0FJTGM4
            NTFGSWRSeFlmS2taUDhxZEJRWFBIQ2sKLS0tIGFNa3RPemYzVUVOSXdlKzVJaTJm
            L2RVdHVqTW1iaTZYN2Q0TDU4UTAzclkKitZDLhmbvtWxw3BDEG93NAkS+RM0eTP3
            GZORfH4VjtuOnmH+v+hCY2wT3jVmhu15LJq+InO211cdB6z/DiHGww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T20:48:18Z"
    mac: ENC[AES256_GCM,data:Sw5NlyS6OcWSi1PGeBup3G/GvUlErCWpQ/1Tq8nxVhXYYRcL6njH+E4ralGWq4lpNBydmpIezSw+z541QXMaTgcDflty5YKbEEaABDLVpIhqN1CRFoCHw8V7JMIogbhiyjFa0v7m/1wn9zfhvHP1Wug+2ThFrXoddBDwUwlTG9w=,iv:DSd02alCnuI1CEjvsqvt6XFUoG95WKeyTMZ0oxhkaMs=,tag:Q40dIIR4+xraFco8t4FISw==,type:str]
    version: 3.13.1
