apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: papra-auth-secret
    namespace: papra
spec:
    secretTemplates:
        - name: papra-auth-secret
          stringData:
            #ENC[AES256_GCM,data:q9Ey3wx7cPIBiy6f5QOLQVCPEKATafnVQAHmDfHUgWigXuXYMwtpDq0ezVc5LImgWkE=,iv:tO5wD+4iL4qV55nJCh2sPdCstSFaOWfLkiB2qcZaQz4=,tag:DXayIs2RZXjHpzZf+aDsng==,type:comment]
            #ENC[AES256_GCM,data:RlIyehBwhCdXvGth9+CswnEhoHnjALa0PxCJW/E7OjMVeg8=,iv:MXYOF3X8YCmlC0bwMEzoXbu6IZAVvHLrK3fWjWpbt/U=,tag:BB33D3qKdP/xeI9DOzAcag==,type:comment]
            #ENC[AES256_GCM,data:fbkqBUXR0gl3JBGCzf3vE2Z5DZY+t2L3UGfncPJKEm1+JYMh23lTPUtfP+XRTILAFPEgpIXjuhn65CenpTYmaOS9,iv:mSxI2SpeEmaZ/IVICkF+/ftABlErCvmuGYndz4RprGU=,tag:9kEgLMSthIKNdSPzx4mM6Q==,type:comment]
            #ENC[AES256_GCM,data:Em/NHfnBUTVWmvnoXSkrHKGq+934U7c79y0+GfwrcJteJxUnY+MLY43R3wzAufe6nuaXSKSV3Jyk,iv:gnLOOa/u9HQHyQ79GJuXFxiTDUuWIBXuhgKf95VgGfk=,tag:23scNoxkKvURuvB5NNaaXA==,type:comment]
            AUTH_SECRET: ENC[AES256_GCM,data:DwrCj+4obqUVWlsp+qAjoCOaiC7az2/5vTiIDxfhXutsxzUnd2Hqc6ijiRQR1Pwbvy7ywli2aUx/sQH8roVMcZFQQ30kfysjXDa8KCba0rd8S1SWvd3EkbqisDwSXHR/,iv:4ciH39aAmGqyBRGOY1nEZrvPmHjgtL2vznAWs9qRaYs=,tag:X1rqf4+N/wtGQXUTldDFJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxV2FEZlBOOHhIZzg3Zndj
            K2N2ZkN5TTNqQWswQ1hsWjNQbHpTd0FpNXcwCktPejdjU3RYK0laMHg5bmVWaHg0
            MFhmOEpqajFieTFtZ3N3dG9vQW1MNHMKLS0tIGR1NGpJSGFPUVVhbWhGRFhSalQ5
            TWRRUmJiTHAvTExWeVY2bTdiRmJrYTAKgp4H9t4/cUtNDlNhKkD/mOyi8jkGMwbj
            QB07tJLxsCpAexcd5cE++rrgsxDsP8drmrBk3VPdyNY0wnkD8+qVOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T12:29:06Z"
    mac: ENC[AES256_GCM,data:qwwZDgztTIjS8JFl0ppVOW9CKEMXzg74WJHmMOnMu7/cjbG2WL1LtZ1a4oPIHzoO8dMfdrw79l2Kxt7Xxk3fBzd9Axw7f8G3LMVYPNtsxIxtF4lvue9qPfLBLq38ZVCmmqutW3aTDW1z3SVlETn4f6LcWO6XZriWSpDDxw4JoHk=,iv:qibMTQsJ+YFUrjWCa0tjiASA/jwSOelXoa+VtqOc7Jg=,tag:YV+O0fntU3PPEyNi3O4WgQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.0
