apiVersion: ENC[AES256_GCM,data:XtU=,iv:XHlvyndredzrKn1dL9rZGc9EMeEWp/7qlNYF+NY1VEY=,tag:J0IWxnpkv347hObwP9c5QA==,type:str]
kind: ENC[AES256_GCM,data:C9PlYGru,iv:Km85awkOtSTgGAVVtaAZcGLIWQwdUKJKsGF4ma0lyug=,tag:WERqe9p5leZx5TwRDW/wvg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ysay4my/WosQocMN,iv:h0m/chrS4kgvYXNWHhGteH3kEHsU49AdZYZ3/HaIbp4=,tag:NEGloeP61aepiBTgKvAB1g==,type:str]
    namespace: ENC[AES256_GCM,data:W+gNyt97YBz+I37R,iv:SiniSJ6rJ8r8lkA97UvPiCuf5QWg9WJ32q5ZuOi3/bc=,tag:OVuYuVj/XyRAxaMLlywBXg==,type:str]
type: ENC[AES256_GCM,data:PmRJobq5VFzTsjyvi877MYc=,iv:QA7wZXTTL/tkie28EdOuze41fm6SWQxFo91yzap4jGQ=,tag:y6CwkOc6BRUcj1NYLI6k7A==,type:str]
stringData:
    tls.crt: ENC[AES256_GCM,data:E/w7Vi9DjLSUL9b5MrlNNvU9L57zGP4JjAZBAC5FavAGdG+Pq/MHB0/YHCZZfQrZAXytjyosFd3J/aU67fGhODwpWFk05iPBAXwRN65Bpo3U5KQeSoHn/bpDP5u1PGKLIOx6C+gaUNmT5S0sk/nS+5djwMTaM7txACZsaKIXSHQFxVLjMvhm/zIDM8tZREjusVcaS5bW78whOKEdo9red3HyRdLalusRY3ELu+m6t/9s4NF5ZCagsvWSscT+GTPS7JNio8VHBwlzm4gEiNR0IsdRoGP7NanjoaNZzA+wleGtpIkpEdQ4brDcTqLBNcLFKsqNVdMYfXdMJjCfWWZ7HLGJzOqUld8/7PP1fMW4pvt0lDqe5roZrUXAmvX2mszzC1h8uwn36HvyjfWKJk+yApQrQJxr1YaCtCVJR9tFEnCo/FpsoSdwW21bFwNN57V0PmErn6B6k0NF5zpUTq72p6vg26wQYKNCsV2UYQl6oqbJf91BlQaoHzcmrvv6urjnbd7eNGjM4hGPuUF54UHAzEn+WIwiMHLrTYrXQC2N3Fb0scJTJlUB/owYPA24+QFMBgoPVX68pcjEwse2czcpNQVR9Cx94jaz5nRMgzgkhpptySz5MzdunBgR+S72owZvVkhMC+F5fiF2vRa0AxRozb9Qu2J0s9fuB1wwX2nNdFCQlQoMhVluBTUZ6Lf2zSwP2aaTFg9ReSm9YuypCl2ioSdiguOUJjlZWfLMfedED3xEX+886Rit9xyGWKJWzcrdF8oMKexZSplGrWlAJ8s6BTImGml7/jZPrtVQcQ1o2FxmvgR8YeBvRQHtRz3kLLSo6XTdpNm7dOT197xoBFoMjCbU4/dQtTOI,iv:NhxurUq5+3+YjMUYZPTlvgZtoFSlk7hxqdEkT1zI4wY=,tag:a0eeDD3qh0cdbQil8iuBBQ==,type:str]
    tls.key: ENC[AES256_GCM,data:L8OOk3Xw3xzM1pFwreBnpd39k+a+jE5LRR6me2HNmo4q6rPh92r8yLw12CcNkMofxNkVi8PHovl1wU0YA8qzI0wyXOeaLEsMtS2PSRrsQaVy2Umi+wxKZ3g4urpTiYZ5giOzjW1JXh9fZTuL1nIIWrrAyx4dDBwa5mBp83aGWQRuU2i6s+CAZ05kX2zzCJyn+dnUJLpPo9Dy4f33vf1x5fiLkJGFWh/3dilU1x3tPa43ZT7gfUY8zalRuOIlj6KOg4j4N6JBbEsNeSnZP4gDltRCmRwrEQCI6Qe1NlnsjxNjeLD0CIDmAXxmIqf7YHnDgLPc1IJqzXw07+lDWEqZsvbM6fEiSQJWFMBcb02N+bKTeYk9yrE88khTbawv/AkJ,iv:JwhZxS0W9YbLE75f+2bnGhE0qd8PSMfGZ0HtgIItQmI=,tag:X0vWwTaRFDWB9y29DiuxAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fh2yetxtj5apky38q4qek4qcd69pklgpqe8etlvxc047znkcwflsfa798z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbGNSQ0RLVFZyWTZxSlNO
            QzgzTGZPS1I2YlR5R3krN1ltanE3NmdTcm5rCjFBd0k2MWg3bGtVVnIvMUc5Y1lr
            MFZIbnVoNXNnUkh1cGNPVUZvK1dGV1UKLS0tIFk2V2c3TkNZcW9vVGo4OVR4b1FF
            NWlSNzdtS09Xb1RsdEZoN3FHY2RrNmMKRBQnRwDZnSoWmbj7/XvE4CpJjOo2+tMN
            lxd/5ZgQLerlNHojKH0eiXt5SRSIdKHFv0vGijYNOh2feEdNXJ/UUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T22:09:06Z"
    mac: ENC[AES256_GCM,data:GtNyEqAjq5lGn4UUiC/zDCXDY789dfyyu34Nx4HtEbE/XAS50QFGCrHnY6z0UerdepYvrvKbA7kXsGbeHBmw6j8kJGO3ODb8dUK0Z7qLBM5YwkBLzbaxS7QA4m76qOeDCAFzJDaW8APrzCcG1WGv9fN0y3ekzlJnrdE67xGRYcI=,iv:GsXSWeTAqC6oPNQYnfyWoOJIuj/o9LiT+/Ot7BOwajk=,tag:hVNOG7BIFSxWkrmDGEolew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
