apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-db
    namespace: immich
spec:
    secretTemplates:
        - name: immich-db
          stringData:
            DB_PASSWORD: ENC[AES256_GCM,data:j1QZAHNiputiOYGHY62laTiSqNJdpruZijqOJ7B7NUyCF8b2CWtyGQyh5cNgciWj,iv:fWpLnQfGIMsED10R0mL37TaJuvtxYZR6FbAL4HgfvEI=,tag:RGYy9JVmBRSTNvHh+MhyGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZ3NRUUdUQU1DSCtTd29z
            RlpqNDdmMGRwdEdQVXgwbW5NVUZqNjQzVENNCkVTeUtMZlptK3hEY1N4RGFvelVm
            b1FDTUcwUEZyK0VQRGZrVjFqVnpVWUUKLS0tIHllR0xtd3F3cWsvRllrWFNjZkNo
            THBaZVBoQjBmaWFsS3NDNFY2R1hmZFUKMXq0jFWbRvEop/ltaA29ywCc75I5QDO7
            BO5zZAhtLL2qDrw3QygyTsJCKgyIGf49Iv2XJ/AIbXi/kmbQdTirVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T19:53:50Z"
    mac: ENC[AES256_GCM,data:6Oo9XqzGtIdOqeDZV0FYf9uN6KdeBP5yeFFybkH0Osj+zy+GoAzTBJy8cxOI5iQgRwhsyFUPhOZmRIjXJjEYzP2vBAXspPYGhKchMnRmrFAx83rMgQsAvb8Iw1TNMkVP48IfxVR/SduGr1mLu1YVWRJZ00jcb+k98URJ+Wy/WmY=,iv:Cb5oXFzHc12/DopTOLcyGPxhx+w62w+fEPpjrlKKk5c=,tag:XLIlmUqzP2vi+FbUOX0qig==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
