owner: apps
enabled: false
components:
  - name: matrix
    namespace: matrix
    chart:
      repo: https://halkeye.github.io/helm-charts
      name: synapse
    route:
      hostname: matrix.apps.home
      gateway: apps
      service: matrix-synapse
      port: 8443
      dashboard:
        group: Comms
        icon: matrix.svg
        app: matrix-synapse
    valuesFile: values.yaml
  - name: hookshot
    namespace: matrix
    chart:
      repo: https://arch-err.github.io/charts
      name: hookshot
    route:
      hostname: hookshot.apps.home
      gateway: apps
      service: hookshot
      port: 9000
      dashboard: false
    valuesFile: hookshot.values.yaml
