apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: kanban-auth-secret
    namespace: kanban
spec:
    secretTemplates:
        - name: kanban-auth-secret
          stringData:
            BETTER_AUTH_SECRET: ENC[AES256_GCM,data:VGwrKp6LaJsY8gg4vocySb26Ug+4LfeKj0bUWzlexA5PBZ3N3clGVeSZ7lnpD29j,iv:xENonlTLjUcDxDp814u9AEobV6sUQNnf8mkqubr6ZP8=,tag:o6Tv1f6iU4vj236WXLf8tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5R0pPL01XczE2djU3Y1BD
            cDNUS1hwb0h5QUVKK2lEaTVRYVk0c3ZKVnpFCkhtVnFTeWtvNEdIRVNyTFFUcERh
            cnl3TFRvbkhSQ3VJMTJjUlhXeFFXNnMKLS0tIE1oSDlibGQ0R3pMS0k4Z01HcmNy
            VEQxTWEvQ0dBdFNqeVBuYkdCamxlbE0KZZ1+SA70hE1Z8h42XvF+btPyrbmW2ci4
            iqdVbaWL02j6pW4XG/FaBIH9JWJkgC4oXwh/xQ5qFU6JothbCVflHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T20:51:12Z"
    mac: ENC[AES256_GCM,data:maxooblVkMsJj9FyX3hW+2y5x8evaMXKwjacXLtVXyGWgcr4C8F845uUawaBuhCeaGZMQGGo+KAwtuoHUn0e+hzuZL+esJYBKarXHdXLESQq0ZZh7dnsL8esd4vaa7DkuWRm3xOrg+54oueuQtw8k8XgnGr9Z1TZw1VbAGCkpXc=,iv:ZEfj0OXgWFEq5Lsqvlwl4DqNFvnAbdqSUW3M2hAt5uU=,tag:Q1O1WkcYKp+ZS0jbwsxiHA==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.0
