#!CMD: helm upgrade -n fakedns fakedns .
services:
  - name: "vault"
    host: secondary
    port: "6080"
    homepage:
      enabled: "true"
      name: "VaultWarden"
      group: "Security"
      icon: "bitwarden.png"
  - name: "pihole"
    host: secondary
    port: "9080"
    path: /admin
    homepage:
      enabled: "true"
      name: "PiHole"
      group: "Management"
      icon: "pi-hole.png"
