#!CMD: helm upgrade -n fakedns fakedns .
services:
  - name: "vault"
    host: secondary
    port: "6080"
    homepage:
      enabled: "true"
      name: "VaultWarden"
      group: "Tools"
      icon: "bitwarden.png"
      # siteMonitor: http://secondary:6080/admin
      # statusStyle: basic
  - name: "pihole"
    host: secondary
    port: "9080"
    path: /admin
    homepage:
      enabled: "true"
      name: "PiHole"
      group: "Management"
      icon: "pi-hole.png"
      siteMonitor: http://secondary:9080/admin
      statusStyle: basic
      widget.url: http://secondary:9080/admin
