apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pocket-id-secrets
    namespace: pocket-id
spec:
    secretTemplates:
        - name: pocket-id-secrets
          stringData:
            #ENC[AES256_GCM,data:RVcinkdaZZxXg+5Fm+PJTLEX4xMOlvfsa8Sk/nBLlADvp1RG8Tt64CpD2M/GGxp7xT76fq+/ENq7uA9msZQac7Mo,iv:/cg0YyjTdchoaIT9JNaQAQsgOCjl+3cfwgam+HDNOS8=,tag:u+TVzOpLnOJ2aFzrfYQOzw==,type:comment]
            #ENC[AES256_GCM,data:N63BF6fFck/dn/7UbYFw8uLbRzM4dv72Pa5Irpu7HvVBT2nYlDEjFlx7nXJQ8815b4KjeSWXeCS2t2LejA==,iv:6CKJc8YRmcR+K7ySGsxQyzC//9QlFF+nBJkJYIVauns=,tag:YKdMUj2r1N9pqb605CYesw==,type:comment]
            #ENC[AES256_GCM,data:Oi/y/EqxQYWcA8tsNFRqzL6Ad03nMmtw,iv:BscZroivyxz1S5qhHrjRgV5bYww/25xGuUtu6gOyIdE=,tag:aNqJVqpNhwPOSovZ2bKfwg==,type:comment]
            ENCRYPTION_KEY: ENC[AES256_GCM,data:I3WJ4PXqU7eFWwy1IGmhK1K7J3U1+6CXSR+/LaxIqVBTJkExQEXpu3mfVtc=,iv:b4U2v2HH6qyMrgtTdPN5pSbbKNYgPjutB5ijJaIM2AI=,tag:gLqwy2SWBESWnstjHz1wjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTDFzOHM3U2N4TFZzczhL
            QnA5cEVXZTRyTEl0KzlRMUxoSE40Y1paQUZZCko0TUxDaGloOXh3SWZaa3NiSUs5
            dHlCSEU2Y0NwaVF2alNIUDQ1M3lCMmMKLS0tIGlDSjFmZ3ZRc2dsdHFKODM0T1ZM
            UUNFTllTeTZIWjQ0K2c0V05zanViVXMKVSLZMhMocjt3huO3Xi04cAM2S3Wi5gmQ
            vZ1ALeT/vGuLHfEZLJ4mmgpA1OqEYW4dbYGe3WFdRSGfDjKEGoUMow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T20:10:50Z"
    mac: ENC[AES256_GCM,data:89pYETeUK1jO11j1r9b98Yma3mKbrhjSfffcM0SkDJp5WgaDDeUZR8IIR4wrv3iEk/DihNHZanomo7r4EPPQfjcmTnvz6xjSghqa26QtJbs4fRruEt5hodGixE1yKIS56loIShWjXFEucXIfCqH3pyylqwfcrUoFnYQX4qYdTm4=,iv:hkxsImUwrzNNYOQ0gvngbTVR6vrqqhNVvr2suD0tbzs=,tag:24rUqncYzXPzy0tFbFWzUw==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
