{{ range .Values.services }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "selfsign-clusterissuer"
#    gethomepage.dev/enabled: {{ default .homepage.enabled "false" }}
#    gethomepage.dev/name: {{ default .homepage.name .name }}
#    gethomepage.dev/description: {{ .homepage.description }}
#    gethomepage.dev/group: {{ .homepage.group }}
#    gethomepage.dev/icon: {{ .homepage.icon }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - {{ .name }}.home
    secretName: {{ .name }}-service-tls
  rules:
  - host: {{ .name }}.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .name }}
            port:
              number: 80
---
{{- end }}
