{{ range .Values.services }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .name }}
spec:
  type: ExternalName
  externalName: secondary
  ports:
    - name: {{ .name }}
      protocol: "TCP"
      port: 80
      targetPort: 6080
      nodePort: 0
---
{{- end }}
