apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: audiobookshelf-v2-admin
    namespace: audiobookshelf-v2
spec:
    secretTemplates:
        - name: audiobookshelf-v2-admin
          stringData:
            ABS_ADMIN_USERNAME: ENC[AES256_GCM,data:B3CaXg==,iv:bVUfmOrUP/J5w8XR6vKwX9gwVphVHQIpAvzRO/uufPs=,tag:7bEHgXUaQqb+evWPFMRHFQ==,type:str]
            ABS_ADMIN_PASSWORD: ENC[AES256_GCM,data:8WnYqhiU4om+hG4EkXTySKw43ogHCNEpBFFzu8Mx,iv:zggdVCpgSgevEh7hXM4k7h27/q7cTTX9vPWhBzpHk/4=,tag:35CqejcWepjnLk6qBiaAsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bWdDdXcvRWh1YjNUelR6
            VWF0TG8reHU5RTBXZU1ncEpzaUlNS0M2WTA0CmY4N2Q0UWNVTzNJcHgrY2JGYlNq
            SXpyV0FEOG8ydEVtTnFqY1hSemh4azgKLS0tIG5ZVU9hVWVqeHVudEptWmlwOHF4
            aHRJUk5aNnVudU4zakVybmc4RkRmalkKiUGDJFgO5wXpEe3GjGo3KylsHoTkICla
            /8CoO8h5eeYRPw+wFSWFvgU9PPelPlqR28Obir48D8joj4O97RL56g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T17:28:11Z"
    mac: ENC[AES256_GCM,data:vFMfb4PU6L1v/vXdMp0NVi3601KMyEqy3zv0e76LleMMcNuyYvSzP+PlSxh+yGvOozrmXIUBhyxAi4j47kwOXjIWaybg3Q/4EpxaKOznT/WFMu9shNV2brnU3ncaGRGRvUD8zSUHJZtRvc/vE6Ha+HOtsTD/jyPcxps6sWCrdXQ=,iv:jZXa46Lq+5560qyOz22tI+6ZTZXqurpD87bGlb/Dfew=,tag:AzxazEwwuVmDCwqBOun9Vg==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.0
