owner: apps
enabled: false
components:
  - name: vaultwarden
    namespace: vaultwarden
    chart:
      repo: https://bjw-s-labs.github.io/helm-charts
      name: app-template
      version: 4.6.2
    route:
      hostname: vaultwarden.apps.home
      gateway: apps
      service: vaultwarden
      port: 80
      timeout: 30m
      dashboard:
        name: Vaultwarden
        group: Security
        icon: vaultwarden.svg
        description: Password manager (Bitwarden-compatible)
        app: vaultwarden
    valuesFile: values.yaml
