apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pocket-id-public-secrets
    namespace: pocket-id-public
spec:
    secretTemplates:
        - name: pocket-id-public-secrets
          stringData:
            ENCRYPTION_KEY: ENC[AES256_GCM,data:oxA6rhC5Vcuak/7VULeoE0WDo2TfWPkkp5Y1QAlFdHhI6FV11HbNC4p+uOw=,iv:TZIN7i1zzbGylBC5rFooMJsbPDua+oEpYFNlCcbFKA8=,tag:8mXZXIm6m2fVApQrJlfugw==,type:str]
            DB_CONNECTION_STRING: ENC[AES256_GCM,data:BD5EBjLceLS/qBVLI2+eGGHkivLuHw==,iv:VquyY2bLMD2ipHT7uh/F3lja/pDOMexiInMLwz7d2CQ=,tag:1SDsbY7p8fftAJMPTiJ8xQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVEpYdDBOVjI3T3JQbzJh
            ODdkc3ZkbHhNWFoxVml0RzkyYit5ZW9sOVM0CjJRUjdQdzBvRlN0d3o1WVRPd20y
            K29COEtidUE4MUJIQU94U0VCZ1NrbXcKLS0tIHQ3Q1l6a3dXSE5EcjBneUQ0aHBl
            NFRDOHN6OEZhaU9jdjR2WnpoM2lVV28KW50I+yfI+6VKrLPBr3azsfStwbS+5p5d
            Mj5ZXb7IOU7MTH3GH2ZbSL6+4ajxmri71Exfo+Ii4PodAIMlOnFDUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T20:17:26Z"
    mac: ENC[AES256_GCM,data:vYQdkYvRb4h5bbJNIXEMd2U4m6c/qZ6xB9XaazP9/VvNqutnaQqt8wv9DW7ilgiiy+JUzzlu9gzCxORb5mLGSDdaDt9xJ8mNYdAYBwd/ieJ7MonyxsOTNkKNi5pssNctKsyArb46xr3qdua6mt2T4qmRZLKTF6PkIpyU22s9dDg=,iv:ctPcp/hvLW5wVqRPFEHnNVBDGinG29cyuckKHX3gpUk=,tag:aqcXOKZ0ccw2PdtsHO7SVA==,type:str]
    version: 3.13.2
