owner: apps
enabled: true
components:
  - name: audiobookshelf-v2
    namespace: audiobookshelf-v2
    chart:
      repo: https://bjw-s-labs.github.io/helm-charts
      name: app-template
      version: 4.6.2
    syncWave: "3"
    route:
      hostname: audiobookshelf.apps.home
      gateway: apps
      service: audiobookshelf-v2
      port: 8080
      timeout: 30m
      dashboard:
        name: AudiobookShelf
        group: Media
        icon: audiobookshelf.svg
        description: Audiobooks + podcasts
    oidc:
      enabled: true
      clientId: audiobookshelf
      callbackUrls:
        - https://audiobookshelf.apps.home/audiobookshelf/auth/openid/callback
        - https://audiobookshelf.apps.home/audiobookshelf/auth/openid/mobile-redirect
        - https://audiobookshelf.apps.home/auth/openid/callback
        - https://audiobookshelf.apps.home/auth/openid/mobile-redirect
      scopes:
        - openid
        - profile
        - email
        - groups
      groupRestriction:
        allowedGroups:
          - apps_users
          - administrators
    valuesFile: values.yaml
extras:
  audiobookshelf-v2:
    enabled: true
    librarySize: 1500Gi
