owner: apps
enabled: true
components:
  - name: it-tools
    namespace: it-tools
    chart:
      repo: https://bjw-s-labs.github.io/helm-charts
      name: app-template
      version: 4.6.2
    route:
      hostname: it-tools.apps.home
      gateway: apps
      service: it-tools
      port: 80
      dashboard:
        name: IT Tools
        group: Tools
        icon: it-tools.png
        description: Handy dev tools collection
        app: it-tools
    valuesFile: values.yaml
