owner: infra
enabled: true
components:
  - name: error-pages-infra
    namespace: error-pages-infra
    chart:
      repo: https://bjw-s-labs.github.io/helm-charts
      name: app-template
      version: 4.6.2
    syncWave: "5"
    route:
      hostname: '*.infra.home'
      gateway: infra
      service: error-pages-infra
      port: 80
      dashboard: false
    valuesFile: values.yaml
