apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: booklore-oauth2-cookie
    namespace: booklore
spec:
    secretTemplates:
        - name: booklore-oauth2-cookie
          stringData:
            cookie-secret: ENC[AES256_GCM,data:xMIh6NkhZxxslo3qHRdWJgX5qdhN2QknEnelsmOkOag=,iv:Ars5Y0U3uE9K5SQ7Xaf3+qcm49/NbUT8aKgClTsv+Pg=,tag:n7rTSIzbolw7jKXVNhaffQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaGVmNDJ5QTQ1SzdRU05Y
            WExaMEdaVkxyb29ZaTZUTHNIaXBrcU0wWHhBCkNtTS9iTUs4ZU91U1JIVmlraVJt
            bVFzdllmZ3R1akJjQkJLY3JVcG9XblEKLS0tIG1BTWlGejViVG9BMnY0bEkvOUhu
            Q0xqT0JMS1pWNGNSZi85aWU2UE8xa2MKQ5c0bqZhH/V8dXrvzU4Q/rLKrofT3iV+
            59ykp7sYJ969UyWYnvAE00J6pR5ghCUbeA5si4lw3jvM7AYOdobJnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T18:25:19Z"
    mac: ENC[AES256_GCM,data:gkVXqseBwILvT0kaGKNhNYPOTj0XxerspKum0AynMczgMK/u5pG3uPRFSDQXGFjQJGHEVkyOfyCzIMedc5g0qCMFTbxiSGvna69mbZAcX0LzLvSAS2+DRsGKePimBl+BWdBgN1wRzKdz3ADujn/9j19dr19yBJZpw9KAGWXUxuo=,iv:xJz2JoNoBnYXHS11EEuuV7ztivjeiowSAZDgHb0b5X0=,tag:j8q7GYGlsW4pdxA/vWiXNQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.0
