apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hubble-auth
    namespace: kube-system
spec:
    secretTemplates:
        - name: hubble-auth
          stringData:
            BASIC_AUTH_HASH: ENC[AES256_GCM,data:NP6ccUuJX/JWrBt65e1zTinDbl+tPhH1kSCEs1ThKovTHd3qowiy83deJQpnCsFEScTQi8w6EbByYDx8,iv:T/M228IWWgcTd7MYOfk2ZeacptjHykdQD1LShIwCW84=,tag:T3mDNzt15ihL5A+D5xmu3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Z3NhK2Y5RmJEWVJONUFD
            QmZMSitSR1M2eGV2SGIzUm9aMEp0V1BLYUJRCm9GWjh0V3E2ajVjVUxKZ3pVMnVD
            QUdNS2M5UUZvbkhlcUg2NUE0by8rTEkKLS0tIG1KdDBlcnh4Z01nV3dGTGtsM3RZ
            Z3BnZGdyR1hFcEVzRDVoNTJTOTBHREUK/G53je+VrwPnwjbpJRbMsh4LrFrKuryK
            TldSGMSYfGt9dqywBvVaCJDVDTDNVIi5drgc7l9tj0Ami1ZpLwEeFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T22:05:42Z"
    mac: ENC[AES256_GCM,data:Ib9zILpJI37qUSXKp+rZkYoLorPwTIP/fYhcD3ceB05lv9a/J+4WUvIlgUxeOx/XeQECOGQNxgxIGwdXQDpv59hOiA4Q+sHh3IKl5lxHfRv3ttAoaYcpp0StS7lOaZKZJ2JJ9DkEp0SuKkPBRmHpD0FUwziTHX3SItomLaVUp3Y=,iv:KJC9MRTwU59nINVclGVW0VSgkbDKZbfk9b/jAUOH8Yc=,tag:/eLtUd/szP2QuDFFdasBlw==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
