apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: zigbee2mqtt-oauth2-cookie
    namespace: zigbee2mqtt
spec:
    secretTemplates:
        # oauth2-proxy cookie secret (32 random bytes, base64). Distinct per
        # oauth2-proxy release. Consumed by the zigbee2mqtt-oauth2 deployment via
        # OAUTH2_PROXY_COOKIE_SECRET.
        - name: zigbee2mqtt-oauth2-cookie
          stringData:
            cookie-secret: ENC[AES256_GCM,data:SH5+HK6PDILK/byitekcL8nRPujrfqhLXeMQBDEUhKCq+9/jFWsSKFG/8ks=,iv:MArHFU4QwXpAC5SCseFotOaOKZRDth5xzSfYo3+xcos=,tag:Ti2jHQyR58m16J4NXpG6wA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVTRuNWg1dEZiZ2xaLzNm
            SlNTRUVqb0tTUHEzQ2RHZzRqSXlLS3YrNWhFCk5uVTE2Q1Y3OVdPZDIvZGlUMnRX
            VlhEWmN1cGR5WjRtNkFiaEpxRXF5alUKLS0tIDlVVnF1YVRCc1NNazI0WjlyQTAz
            dzI0RmRhMkRTU1lzaWlVNDdEZFVVbVUK78nfLim5s2zEMKZEBX+FU4oUnWr5KmwO
            DIeSwVZhojJS4UyLRGqrrUj0W8dQFz1snejsLVgVkGyc5rTPSPTk0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T12:35:31Z"
    mac: ENC[AES256_GCM,data:aM8S4ZuPI1hFJ6cLYYroI6Yo+LAff+rtFUtdO0S4ByA48jQ3k/WIzPT/pLIS9Ubq3xMwOcAgwqKEA/epjUq5I4k9YXty66aonlyz7Iv8+eqEMPejAZ95rxcdZCQn7ynKFgA/HvetYi34QHx46Ec6kngfWM+x2FH9cHdRX+TAz3I=,iv:r6jTjkjiules04YszzE009s2a8WX2sCxlHS3L+a+/Co=,tag:ioi93wPW44pNwFx8ENvyvw==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
