fullnameOverride: myrctf-loki
deploymentMode: SingleBinary
loki:
  auth_enabled: true
  podSecurityContext:
    fsGroup: 10001
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
    seccompProfile: {type: RuntimeDefault}
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index: {prefix: index_, period: 24h}
  limits_config:
    retention_period: 30d
    ingestion_rate_mb: 4
    ingestion_burst_size_mb: 8
    max_global_streams_per_user: 10000
  compactor:
    retention_enabled: true
    delete_request_store: filesystem
singleBinary:
  replicas: 1
  resources:
    requests: {cpu: 75m, memory: 192Mi, ephemeral-storage: 32Mi}
    limits: {cpu: 750m, memory: 768Mi, ephemeral-storage: 256Mi}
  persistence:
    enabled: true
    storageClass: local-path-retain
    size: 20Gi
backend: {replicas: 0}
read: {replicas: 0}
write: {replicas: 0}
minio: {enabled: false}
chunksCache: {enabled: false}
resultsCache: {enabled: false}
test: {enabled: false}
lokiCanary: {enabled: false}
gateway: {enabled: false}
serviceAccount:
  automountServiceAccountToken: false
sidecar:
  rules:
    enabled: false
