#!CMD: gt
# Default values for apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


sourceRepo: arch-err/Cluster-Config

sourceRepoUrl:
sourceRepoRevision: HEAD

apps:
  - name: grafana
    namespace: monitoring
    chart:
      url: https://grafana.github.io/helm-charts
      name: grafana
      version: 8.5.1
    secrets:
      enabled: true
    ingress:
      enabled: true
      homepage:
        enabled: true
        description: "Platform for data analytics and monitoring"
        group: Monitoring
  - name: influxdb
    namespace: monitoring
    chart:
      url: https://helm.influxdata.com/
      name: influxdb2
      version: 2.1.2
    secrets:
      enabled: true
    ingress:
      enabled: true
      homepage:
        enabled: true
        group: Monitoring
        siteMonitor: https://influxdb.home/signin
  - name: prometheus
    namespace: monitoring
    privileged: true
    chart:
      url: https://prometheus-community.github.io/helm-charts
      name: prometheus
      version: 25.27.0
    secrets:
      enabled: false
    ingress:
      valuesSection: server
      enabled: true
      homepage:
        enabled: true
        group: Monitoring
        siteMonitor: https://prometheus.home/
  - name: homepage
    namespace: homepage
    chart:
      url: https://jameswynn.github.io/helm-charts
      name: homepage
      version: 2.0.1
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: false
  - name: glance
    namespace: glance
    chart:
      url: https://arch-err.github.io/charts
      name: glance
      version: 1.0.0
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
  - name: glance-draw
    namespace: glance
    chart:
      url: https://pmoscode-helm.github.io/excalidraw/
      name: excalidraw
      version: 0.1.1
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: false
  - name: portainer
    namespace: portainer
    chart:
      url: https://portainer.github.io/k8s/
      name: portainer
      version: 1.0.53
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
        group: "Management"
  - name: home-assistant
    namespace: home-automation
    chart:
      url: http://pajikos.github.io/home-assistant-helm-chart
      name: home-assistant
      version: 0.2.78
    secrets:
      enabled: true
    ingress:
      enabled: true
      homepage:
        enabled: true
  - name: akri
    namespace: home-automation
    chart:
      url: https://project-akri.github.io/akri
      name: akri
      version:  0.13.8
    secrets:
      enabled: false
    ingress:
      enabled: false
      homepage:
        enabled: false
  - name: excalidraw
    namespace: excalidraw
    chart:
      url: https://pmoscode-helm.github.io/excalidraw/
      name: excalidraw
      version: 0.1.1
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
        group: "Tools"
  - name: metrics-server
    namespace: kube-metrics
    chart:
      url: https://kubernetes-sigs.github.io/metrics-server/
      name: metrics-server
      version: 3.12.1
    secrets:
      enabled: false
    ingress:
      enabled: false
      homepage:
        enabled: false
  - name: unifi
    namespace: unifi
    chart:
      url: ghcr.io/mkilchhofer/unifi-chart
      name: unifi
      version: 1.10.8
    secrets:
      enabled: false
    ingress:
      enabled: false
      homepage:
        enabled: true
        group: "Management"
  - name: cyberchef
    namespace: cyberchef
    chart:
      url: https://charts.obeone.cloud
      name: cyberchef
      version: 1.3.0
    secrets:
      enabled: false
    ingress:
      enabled: false
      homepage:
        enabled: false
  # - name: kubeview
  #   namespace: kubeview
  #   chart:
  #     url: https://benc-uk.github.io/kubeview/charts
  #     name: kubeview
  #     version: 0.1.31
  #   secrets:
  #     enabled: false
  #   ingress:
  #     enabled: true
  #     homepage:
  #       enabled: true
  #       group: Management
  #       icon: kubernetes.png
  - name: changedetection
    namespace: changedetection
    chart:
      url: https://charts.alekc.dev
      name: changedetection
      version: 0.5.0
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
        group: Tools
        icon: changedetection-io.png
  - name: paperless-ngx
    namespace: paperless-ngx
    chart:
      url: https://charts.gabe565.com
      name: paperless-ngx
      version: 0.19.1
    secrets:
      enabled: true
    ingress:
      enabled: false
      homepage:
        enabled: true
        group: Tools
  - name: zigbee2mqtt
    namespace: home-automation
    chart:
      url: https://andrenarchy.github.io/helm-charts/
      name: zigbee2mqtt
      version: 9.19.0
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
        group: Home-Automation
  - name: ntfy
    namespace: ntfy
    chart:
      url: https://geek-cookbook.github.io/charts/
      name: ntfy
      version: 1.1.2
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
        group: "Tools"
  - name: minecraft-poc
    namespace: minecraft
    chart:
      url: https://itzg.github.io/minecraft-server-charts/
      name: minecraft
      version: 4.23.6
    secrets:
      enabled: false
    ingress:
      enabled: false
      homepage:
        enabled: false
  - name: minecraft-rcon-admin
    namespace: minecraft
    chart:
      url: https://itzg.github.io/minecraft-server-charts/
      name: rcon-web-admin
      version: 1.1.0
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
  - name: minecraft-router
    namespace: minecraft
    chart:
      url: https://itzg.github.io/minecraft-server-charts/
      name: mc-router
      version: 1.2.4
    secrets:
      enabled: false
    ingress:
      enabled: false
      homepage:
        enabled: false
  - name: minecraft-influxdb
    namespace: minecraft
    chart:
      url: https://helm.influxdata.com/
      name: influxdb2
      version: 2.1.2
    secrets:
      enabled: true
    ingress:
      enabled: true
      homepage:
        enabled: true
        group: Monitoring
        siteMonitor: https://minecraft-influxdb.home/signin
  - name: open-webui
    namespace: ai
    chart:
      url: https://open-webui.github.io/helm-charts
      name: open-webui
      version: 5.4.0
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
  # - name: authentik
  #   namespace: authentik
  #   chart:
  #     url: https://charts.goauthentik.io/
  #     name: authentik
  #     version: 2025.6.1
  #   secrets:
  #     enabled: false
  #   ingress:
  #     valuesSection: server
  #     enabled: true
  #     homepage:
  #       enabled: true
  - name: n8n
    namespace: home-automation
    chart:
      url: https://community-charts.github.io/helm-charts
      # url: https://arch-err.github.io/charts
      name: n8n
      version: 1.13.4
    secrets:
      enabled: true
    ingress:
      enabled: true
      homepage:
        enabled: true
  - name: yourls
    namespace: home-automation
    chart:
      url: https://charts.yourls.org/
      name: yourls
      version: 8.3.7
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
  # - name: <++>
  #   namespace: <++>
  #   chart:
  #     url: <++>
  #     name: <++>
  #     version: <++>
  #   secrets:
  #     enabled: false
  #   ingress:
  #     enabled: true
  #     homepage:
  #       enabled: true
  # - name: <++>
  #   namespace: <++>
  #   chart:
  #     url: <++>
  #     name: <++>
  #     version: <++>
  #   secrets:
  #     enabled: false
  #   ingress:
  #     enabled: true
  #     homepage:
  #       enabled: true
