#!CMD: gt
# Default values for apps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


sourceRepo: arch-err/Cluster-Config

sourceRepoUrl:
sourceRepoRevision: HEAD

apps:
  - name: grafana
    namespace: monitoring
    chart:
      url: https://grafana.github.io/helm-charts
      name: grafana
      version: 8.5.1
    secrets:
      enabled: true
    ingress:
      enabled: true
      homepage:
        name: heheh
        enabled: true
        description: "Platform for data analytics and monitoring"
        group: Monitoring
  - name: influxdb
    namespace: monitoring
    chart:
      url: https://helm.influxdata.com/
      name: influxdb2
      version: 2.1.2
    secrets:
      enabled: true
    ingress:
      enabled: true
      homepage:
        enabled: true
        group: Monitoring
        siteMonitor: https://influxdb.home/signin
        statusStyle: basic
  - name: prometheus
    namespace: monitoring
    privileged: true
    chart:
      url: https://prometheus-community.github.io/helm-charts
      name: prometheus
      version: 25.27.0
    secrets:
      enabled: false
    ingress:
      valuesSection: server
      enabled: true
      homepage:
        enabled: true
        group: Monitoring
        siteMonitor: https://prometheus.home/
        statusStyle: basic
  - name: homepage
    namespace: homepage
    chart:
      url: https://jameswynn.github.io/helm-charts
      name: homepage
      version: 2.0.1
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: false
  - name: portainer
    namespace: portainer
    chart:
      url: https://portainer.github.io/k8s/
      name: portainer
      version: 1.0.53
    secrets:
      enabled: true
    ingress:
      enabled: true
      homepage:
        enabled: true
        group: "Management"
  - name: home-assistant
    namespace: home-automation
    chart:
      url: http://pajikos.github.io/home-assistant-helm-chart
      name: home-assistant
      version: 0.2.78
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
  - name: excalidraw
    namespace: excalidraw
    chart:
      url: https://pmoscode-helm.github.io/excalidraw/
      name: excalidraw
      version: 0.1.1
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
        group: "Tools"
  - name: authentik
    namespace: authentication
    privileged: true
    chart:
      url: https://charts.goauthentik.io/
      name: authentik
      version: 2024.8.2
    secrets:
      enabled: false
    ingress:
      enabled: true
      valuesSection: server
      homepage:
        enabled: false
        group: "Management"
  - name: metrics-server
    namespace: kube-metrics
    chart:
      url: https://kubernetes-sigs.github.io/metrics-server/
      name: metrics-server
      version: 3.12.1
    secrets:
      enabled: false
    ingress:
      enabled: false
      homepage:
        enabled: false
  - name: unifi
    namespace: unifi
    chart:
      url: ghcr.io/mkilchhofer/unifi-chart
      name: unifi
      version: 1.10.8
    secrets:
      enabled: false
    ingress:
      enabled: false
      homepage:
        enabled: true
        group: "Management"
  - name: photoprism
    namespace: photoprism
    chart:
      url: https://andrenarchy.github.io/helm-charts/
      name: photoprism
      version: 8.4.0
    secrets:
      enabled: false
    ingress:
      enabled: false
      homepage:
        enabled: false
  - name: linkwarden
    namespace: linkwarden
    chart:
      url: https://fmjstudios.github.io/helm/
      name: linkwarden
      version: 0.3.2
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
        group: "Tools"
  - name: cyberchef
    namespace: cyberchef
    chart:
      url: https://charts.obeone.cloud
      name: cyberchef
      version: 1.3.0
    secrets:
      enabled: false
    ingress:
      enabled: false
      homepage:
        enabled: false
  # - name: pingvin
  #   namespace: pingvin
  #   chart:
  #     url: https://qjoly.github.io/helm-charts/
  #     name: pingvin
  #     version: 1.0.1
  #   secrets:
  #     enabled: false
  #   ingress:
  #     enabled: true
  #     valuesSection: common
  #     homepage:
  #       enabled: true
  #       group: tools
  # - name: kubeview
  #   namespace: kubeview
  #   chart:
  #     url: https://benc-uk.github.io/kubeview/charts
  #     name: kubeview
  #     version: 0.1.31
  #   secrets:
  #     enabled: false
  #   ingress:
  #     enabled: true
  #     homepage:
  #       enabled: true
  #       group: Management
  #       icon: kubernetes.png
  - name: n8n
    namespace: n8n
    chart:
      url: oci://8gears.container-registry.com/library/n8n
      name: ""
      version: 0.25.2
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
  - name: changedetection
    namespace: changedetection
    chart:
      url: https://charts.alekc.dev
      name: changedetection
      version: 0.5.0
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
        group: Tools
        icon: changedetection-io.png
  - name: paperless-ngx
    namespace: paperless-ngx
    chart:
      url: https://charts.gabe565.com
      name: paperless-ngx
      version: 0.19.1
    secrets:
      enabled: true
    ingress:
      enabled: false
      homepage:
        enabled: true
        group: Tools
  - name: zigbee2mqtt
    namespace: home-automation
    chart:
      url: https://andrenarchy.github.io/helm-charts/
      name: zigbee2mqtt
      version: 9.19.0
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
        group: Home-Automation
  - name: actual-budget
    namespace: actual-budget
    chart:
      url: https://dasmeta.github.io/helm/
      name: base
      version: 0.2.5
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
        group: "Tools"
  - name: ntfy
    namespace: ntfy
    chart:
      url: https://geek-cookbook.github.io/charts/
      name: ntfy
      version: 1.1.2
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
        group: "Tools"
  - name: uptime-kuma
    namespace: monitoring
    chart:
      url: https://geek-cookbook.github.io/charts/
      name: uptime-kuma
      version: 1.4.2
    secrets:
      enabled: false
    ingress:
      enabled: true
      homepage:
        enabled: true
  - name: kuma-ingress-watcher
    namespace: monitoring
    chart:
      url: https://squent.github.io/helm-kuma-ingress-watcher
      name: kuma-ingress-watcher
      version: 1.1.0
    secrets:
      enabled: false
    ingress:
      enabled: false
      homepage:
        enabled: true
  - name: uptime-kuma-credentials
    namespace: monitoring
    chart:
      url: https://ameijer.github.io/k8s-as-helm
      name: secret
      version: 1.0.4
    secrets:
      enabled: true
    ingress:
      enabled: false
      homepage:
        enabled: false
  # - name: <++>
  #   namespace: <++>
  #   chart:
  #     url: <++>
  #     name: <++>
  #     version: <++>
  #   secrets:
  #     enabled: false
  #   ingress:
  #     enabled: true
  #     homepage:
  #       enabled: true
