apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: agent-vault-master
    namespace: agent-vault
spec:
    secretTemplates:
        - name: agent-vault-master
          stringData:
            AGENT_VAULT_MASTER_PASSWORD: ENC[AES256_GCM,data:rIrYj8YxkBkZghsCECxOL+qzdQ2eDAPz7j6N9y2gLpUJGUX8ou5a46wHVntD1wGtVVAgDyconPRMu59bvBh4dg==,iv:+4dSUgEjUbrTvnqsVzNlBHM/O4J1q30Bym/G4xsWsBY=,tag:x2nnFN8DhF1gw35f35Vexw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNVd1NUxSK2dIUmhFcjM5
            Qk41T2k5T083NGJqUWhWS0cvd1hqRlNkL1JRCnNuUkczOXkwN3JzVEZmazd5VnNl
            amE2bHhVcUlEMzlKVmJpam1hYTZ4WDAKLS0tIFNQLzZzMHFYMkJRVFQvdStMWCtt
            bVVYd0FYdEZXcUJMMXdjY3pSRGdNc28KeyCx+U1rqsYJi1SdcfjAFSLy4ls27Hi4
            wXNkbRhaJmP6QMi2Hjx8UalcRyDdsacnoKEKowk38+MHx4DO/lDF+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T13:11:14Z"
    mac: ENC[AES256_GCM,data:dKaiqqIK0OKU+i1y60DkOB5ZNKv1Vw1hECfbd+kIuV86IPGjkte72D496mElINsFFb9hameS8YIwEB0z9phi9bvI7V+IvGBX9MvHaH7IiGEzi2StM/GnQMD2E+sYns/RB+/Z+NPtCxxziiP42nwb743C4fhxN4n3oHaAN6fJRXE=,iv:6kS0e+HFExpa6T1Hgt79lErttZ/+eY0TuajOEin+wxQ=,tag:agVJYQrDNL2C297lvUznnw==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
