apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: arr-api-keys
    namespace: arr
spec:
    secretTemplates:
        - name: arr-api-keys
          stringData:
            #ENC[AES256_GCM,data:hMZmghAAQ4mbWuPIIt2+HT1jHffPgY3MpNtNY0m7gVXnCkvKjBlUCYncVw1aSZ/gbkzv,iv:ur5P8M7dpuBq3cgO4PnmaqqTHMTDc2q9+PwTAnlMIhM=,tag:8uVckz+lsUNMkpRRr1SPow==,type:comment]
            #ENC[AES256_GCM,data:FDpicoaB4/GRlpjO8PHF48FFx/CfkFmg7WEuHKTxxL2ZpAq/Tcxao3HULdK52TemAVoOy48WRZddtg==,iv:aCadofZXGNqukTX7JeRTldmnY9AC/RFULNVuwd1BsXM=,tag:yjoGtwLd19wYsX/qHQlCiw==,type:comment]
            #ENC[AES256_GCM,data:f6VZOqcLVfWphCE8260xz+V+4dYRKaq4jzdjS2N17H5192TcziWQnlaX2k3yhnlBEwEpWRqk6wR/XxZ9BvA=,iv:X1pgTd+DTXdJYcA1RBz++qh3/jSwNt/A3GT5Ekazpv8=,tag:QtGbOY5jR9+LYyVmXLeyVg==,type:comment]
            #ENC[AES256_GCM,data:eR1ObJr31LXyd8fwOyjJDdNGggTu6bTGx8gZwfMV0Li7XMHnVqdTPH3lhtx5OsLW,iv:Q+AY/pQFs8i/D7atH/41F+9zpjt9GpBg/euc5jSPwE8=,tag:XG2gwiSdfhsQi1QOCBDWtg==,type:comment]
            prowlarr_apikey: ENC[AES256_GCM,data:kEMo1e/cWLVoNocFuF1y8c/ndsNhxSZ6BfmYdn4Gg9E=,iv:xzlBsISe4ls5IlomwWLYHnbIXNL+wxQOOwffQfWwuE0=,tag:NPreZKqx9AGUB2my66Fk2w==,type:str]
            readarr_apikey: ENC[AES256_GCM,data:YXHCU/Z8ZIIiaRCFhwjPxgjyBzfkLzSm1cvlrpHj/uQ=,iv:06Bq47yodRIi58+3hOYt6u4RnmNCFrzUFQuBVqTesIA=,tag:PnejtUCPd1o4i9lqBAR3/A==,type:str]
            #ENC[AES256_GCM,data:aYwt1IIHpyft6Husvg0+3T/pign1s7s+Wul9e78OVUTDI8z3Ov2sry4658A6TKK6mmoc6S4PEg==,iv:TQzoEBSpl7V4YQfkr72omLlXZB2QfMA3TfnCdge+rCs=,tag:Vg4GmMSxB83HiEoz+V7cwQ==,type:comment]
            #ENC[AES256_GCM,data:IysBx6WFRcwXjFcZ06L35La/fh5unTmaDNYRUbvxPompPZ5eu8NEf/rrm9v4bzRsnYTWRLcHVrd9wlTyS3LF91/z,iv:0Kq7ilYI4JcuIlaJ4bOR5DtGo+g5s/CG3ahG8OUSY9U=,tag:D9tSqZ6i09bidRacfOcAMg==,type:comment]
            #ENC[AES256_GCM,data:Inb7dwiUVmgLruD5+fCVQfl9IL4Jv9gcJmyV/8aI6WZugwU1+15kXGhxYMfus780,iv:vEKU92bovht3ZgaLX0dBcgEzutdaX7QPElumAd+DCVk=,tag:ZpXpZ9VBGXEX10mPhBBsGA==,type:comment]
            #ENC[AES256_GCM,data:QIJE/zkui8UNKhAQFwdt5GYw08CKng73/lT9NCJzTW4/txK9AcPKvNjHTTow20Tx8NkAYeaXzRifGEW3syU=,iv:Nm96TnJ9I87h1r7Crhx+dFV0KQ9Gb2D5eMZeoebO8nk=,tag:FzxxzxjeZ7lhg4oPF3gbtA==,type:comment]
            #ENC[AES256_GCM,data:s2zlwpPkuRbGcwkrJh1eioa/uCqS65A9a091b2NyF9zmEg==,iv:q/gECr+Ibb7AOodirr/kERpdguEFTEialLW3HUYeB1E=,tag:w5hhCQ+yvPKcpsA6ES8wew==,type:comment]
            qbit_password: ENC[AES256_GCM,data:Fy1Dod83AHPgnQ==,iv:uQ/6DVhHnYmjbx2EN7lvPjjei/UVlLlll3KEILJufuo=,tag:VbyxxqBV/0DQVZ4JdA/bxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRXBYRGpnNkRuMWVkVlhK
            SzNHVHpCSGxHTFgwUFBSS3BseDc0TWdNeW1FCllxc3VibVU2SlZwK3lLY3hBTTJi
            WE92bVVpQ25IckZPN2JiaEw4Szh3WmMKLS0tIFNSRGJtN1o3Q3hSb0lzL1F3c2ph
            eGdQc2QvMkw4YWNpVUI2K2wzMW1wNEEKLu4OZiujyBOThcx3+iGdaB4/HZZeMT+H
            zl3aAe10ildPgeY06km6r7aL+55hLnDaZgK5i4k9KRRZ0Woyt0nLsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T20:59:47Z"
    mac: ENC[AES256_GCM,data:s1tSoxLaGxtKmcBGW+OwRcm4a+YIWSsFeGv5p+6XGS0H6epjNfq2oUd2CEtVsb7WVG42IKSaddMgnEcdUCbHwBzDxR+aPs5ETIjE5cVUh6VeQO18SrstMEuIJOOlQxoKDHYSRKILrZtoVfzfS79mdMazmXbwnrHnEDXmUFN9KeY=,iv:qDO/uOx7IBXPhvWhJKmTTm8u42U1cANg3nBrnamgzeE=,tag:+vup22uEhXxvGmIkjb7/SA==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
