apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: arr-oauth2-prowlarr-cookie
    namespace: prowlarr
spec:
    secretTemplates:
        - name: arr-oauth2-prowlarr-cookie
          stringData:
            #ENC[AES256_GCM,data:0dS35YgE3E6UV3Ris8k33fkemUzZrzD0Qwiuy1wAjpIWi7JXxEqEU/nVRlSYPLemZSFt,iv:QNr8kHfmZqxr4Ym/jj8xtY+2P2aQuUyWKjbCnxKtn74=,tag:DAPNPRnuu3bdDj0acaOoxw==,type:comment]
            #ENC[AES256_GCM,data:93sU3t4atLfn0DxdZebFLIQY6HUfp9LMtNXhUAEbYPqPGYgo+Hvj+saC6hSNe93+mtQzgF3Q6cfRj5hHb784sV5ciOo5lw7e9s+P,iv:0D1Q/aJpM68QV/Q2rjuQuXQxg0vT1/L7uSgd++QyToY=,tag:waCZuB1krLXAZkj8lKvuDg==,type:comment]
            cookie-secret: ENC[AES256_GCM,data:/zLsSgMS9dIpY0wys1yedZhIGp8SqbPiVyh0M2mTa3g=,iv:+keTY3i7rFU0gyYQTnQDy4gv9Em00j1P6A3AcjqY60M=,tag:3JS177++SSIozu+NKJKrbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoS3VpT3JyWnJsbjExQW9i
            dzBKNU56a2h4OFFqcGszNVYxdzFJZEdRTmcwCnZpWWEvdnNGOTNlaXZSV3ErTHkv
            QVNJV0ozRGFIMGdKTmhBNkJoTG1mS1kKLS0tIFdRTlVtcit6azFGakJxN1J0NVN1
            RnVlTWFkMC94UzkyU25RcjF6cDhPK2cKx1xFxXRqnTcZdhGIBJ3Fg9BSNPFnueyB
            F/IgVLU+olavXrrz3dQ76N7/FXrzt3KpVL5tGEeZS/6TAAMulLcajQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T16:21:59Z"
    mac: ENC[AES256_GCM,data:t0QTl+JumwPQPvc3nNZT3VeLR/zWN6AjLC8NBUJFVyi43rnN0/zgzyS+p1u7sHq+nzmjwHUvQG4SMRpDpuuUFBTQt5CwkX/CIB+1CLLm0dY7Ri2K6W2X+4S3YkzZsp5UGNrsUdNMAZB6NDXsnGdOtntyxI7Dwxc2foTrQ2+gJi0=,iv:hYPQ8/2AQ9C1yGO4o9z/UjhIVdwzMy9aNgSy1pVbmMM=,tag:aFrSTyYswtsx32l+H1Lc7Q==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
