apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: arr-oauth2-readarr-cookie
    namespace: arr
spec:
    secretTemplates:
        - name: arr-oauth2-readarr-cookie
          stringData:
            #ENC[AES256_GCM,data:rYpoxoKJrc3t7ZBCb7/2XiBzSBZj+PFAVvPNzDfIB3SFjU1Osc9Z9Hki7AVH43N+Zg/k,iv:D7iVaQ1xgE4v2a8ol0axMtRb/DYozrge/NmEqzu1G4g=,tag:M77RJTWi83z+Kb7KQALdQg==,type:comment]
            #ENC[AES256_GCM,data:HPoWPpJJz3f51L+JUjwMG7/1AMsY37kW7rFMolOEECLmaoR1Z8RvMy+U04uDP2uNGUznIH1Lp2yCD+GnE82WouA57kHzG1X+esc=,iv:x1CQoYsioOASL6oiaB0airG11zbVso4BOyyJtJ5UZrs=,tag:PNRh+9FQBi+ep5CGlA7Q2g==,type:comment]
            cookie-secret: ENC[AES256_GCM,data:7IC0L713awmLjTFrdQKV/JLD1Sc35tLkIC5RSefTil0=,iv:Fd3sFOn2id8U442Diw8udW1Wy02Jsd7LsfJMN6ii6jA=,tag:xP4sLDoS4KisCCf7cLuMlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjalh3Q3FVQkwxb3Z1UkhX
            K2VmYkkxSC9UTStZWXh0NFkxMXdvb1RjRFRZCkM3L3JTUU5udU1sMmhqaXV0T2kv
            TFZkL0NiVVJqenlQa3EyMko4QmFZd2MKLS0tIE5wQTZCd1JxUElYMlVHU2hvZFdx
            bmY1YldVYkJFRjY0eGlmNWplWWVsWDgKH7bH963C0qPv1JRL9mT5ikcBRzfsyIri
            DpvgeS2lhzGiOKICNzszTmbIwqbXup8b8Ra6V/gU7/tTMrmsve/IzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T16:21:59Z"
    mac: ENC[AES256_GCM,data:arXOO7tvZw2d5elE6bu/MxrJSEU6NklFoTFXfznIvKAs0Ckb1v9huZu4/EsV9NcZv4QNxsLzSclFPlCZLnCPkYr/SAfPYsrVdKU5mC1Yf53CB9XHF+H8r30goH4ONTEBXn5iK8LYM4n/0Qp/0f3UL3NXsZnn8Xsn8IkjqRGySjE=,iv:kaFJ5o542TJ7rE0j7Gv+DZUFpmvI8m0sSZ9pf7EjADI=,tag:J9fpo97WTfGZ8s0GO1DWkA==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
