apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik-secrets
    namespace: authentik
spec:
    secretTemplates:
        - name: authentik-secrets
          stringData:
            secret_key: ENC[AES256_GCM,data:PfH/QDf0FcOh3qIMHhBBkvHM3EpkJB0wjGIzN61U88smtQHMVL963qXNZSYnZCllNub5IXaX6kZgpEVTXnWahA==,iv:anOEw6rVBA6dJ4JQe4hTdPKlmO3DdCeozmtqKxyOwOo=,tag:s57kLDMzc24Ur+XauOONQw==,type:str]
            postgres_password: ENC[AES256_GCM,data:AkKU+IhtxWgw66V2APuA1P3KZ94lHCUwjqcnMOW3/SM=,iv:8j/f/74+6sEZKZvd43jy6zJ9hM3eM7LdpZlaPZivsHk=,tag:GynE/7H6FUuv8MEFaCgMbg==,type:str]
            bootstrap_password: ENC[AES256_GCM,data:FVOB4pdacH1B3AWD6bAJ6rL814I0929FFXBiFtkqvOc=,iv:j6iXbU+cBHIION/uiAptTswh3WSW8zFNJZucIsUWOE8=,tag:BitGqoM6TExv6xxUpQh1rw==,type:str]
            ha_client_id: ENC[AES256_GCM,data:o2l+Ar/1y+BaHs2IJu1NoFjZmGq7QmXdEApS1p9LuB2WSc55RWVrPpO5OU+217N1RJ6pG0Yxh1JfAE1fVlGFkA==,iv:ZFYn2Euox9ZjuIe0Wb895H4M3BA7Xr4Cx6JkUfIcLQY=,tag:IWMDwEKz3yQQJQvxgAZ8AQ==,type:str]
            ha_client_secret: ENC[AES256_GCM,data:oLAyYNzXZHpeCo0oWwgpOGrdCMvsFIlB7XLqDeKffSPZQmaGf+dCLGSlYdm81fUPFnjRdCesOxdS6FEhtgRpMg==,iv:wpJpTe4QFe3kM+kry6AL53mePZmrhtnwYBpVkeVJ54s=,tag:xf/zACSA5nbtE5K6l+geCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K2o4Z1NMNEN3U3J3cEtz
            VUZFWjBXbmpoNFZqVDBuODJlSkVmRDBKK2djCmtodUxsZ3lVcTJYY0thcm9DQzBE
            VCtKRHhTNkxjMjVvb2FJYktIZm5NN2sKLS0tIHBtTlloREFoMFlKdndkdHJGR3hO
            dW51bkpVd1ZRTjFYMTRuT0x6bGF6VXMKwUvPQQp13lJNoW8fNtOhWmSDDonzJWh7
            VyqYQqZCkch1MAoYG1g+a+OyYmgY8NDILBxe06qJrpHyJzuH4ybiEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T19:29:54Z"
    mac: ENC[AES256_GCM,data:XtI7mJQc1A8F7WDyz3annlYQKO+6bVE3nrrPZef9JaV1S0FprYXyfwI1NIMe1sF543u1O9sispW24Ha94cC7XdWU2U8HACPRRmNHoK1U7N32ZmBME1BnFgRTHwuBQP7miNAXDOEkJFRBl/Byy2LdlhnkkF5HSMyvtmFgxki+DwM=,iv:RYAVuW9iFgtETb0wK/++nlg9qs8yltIG3qS9bXjtVhg=,tag:voDBG/DbktcQdYrvAg+D5A==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
