apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik-secrets
    namespace: authentik
spec:
    secretTemplates:
        - name: authentik-secrets
          stringData:
            secret_key: ENC[AES256_GCM,data:8ooeegp2/mwNenZdIVWqAqUJPt4++WVmJWvNP4AcDYr0XLdqF/Sz6ccB38L6j07AY51L7SDpKxLRf3WzD84s8g==,iv:9vKrtB9OegTgRK5gXC8ST7IMKGUnwut4PytSQRfFUBs=,tag:mCZKjzmWxuC+c2fZ9wJgBg==,type:str]
            postgres_password: ENC[AES256_GCM,data:42AojLcsej24aajrDZaDg+S9AP4TcBucV5Doxkzzduk=,iv:lBkTgUMlkR3mPKrtEgiG+zpWcGqvZs8f4D4faxWq8Lk=,tag:zW2KP0AMYyUu50q9+MwLwA==,type:str]
            bootstrap_password: ENC[AES256_GCM,data:N+6kCnEArumQ+3wStnqO6jf/SP7I5CwKc5it4a8kwB0=,iv:qhu6OmXr8caXwHbNV40QCxGyD7Zf9yK2ilZR4OtWQmU=,tag:iPK9EUi26JNqyXUR9Ccc0A==,type:str]
            ha_client_id: ENC[AES256_GCM,data:j6Pk/Z+WrhfY6QId2+wFLxlSJWnGzzxcJbWc7Jhhjq0OwT0ERnahSkkv6ASLEpZF5EZn/9Bm7HsdDDn8pUVs0Q==,iv:/8+63IK8rCDyGgMnpza0NmhDiY96pLOKJx1z548sCHw=,tag:LselSQQt4LyQXpSOabR0aQ==,type:str]
            ha_client_secret: ENC[AES256_GCM,data:+mdGCdIunaWm+azR4AQtpGGPoGpiKn9dTA21rtAKFayfhLCuXIu//IGVLiBqW3aoj9ETRJQz4/rPhOw9H/UEZA==,iv:7lmJa95a/3uB6ijYeIcNasIL35AvreQX9ZsJ4fKyXG8=,tag:DfbXtTygRrQ1zDhxq+2BSg==,type:str]
            argocd_client_id: ENC[AES256_GCM,data:gZpoQHa9HsgNK+r+N9hjwkOahmkapmC845IIFZwXYF533+ftR7gGj9cCwAkbcb/H9c63uTgBeO1ndzzS6oFg6Q==,iv:DcBC0cr5dpi5FTzilmQrQWsMmCVtQn/y6K+PSgZE9mw=,tag:qZVxtiKnRJy3cdM5iPg8JA==,type:str]
            argocd_client_secret: ENC[AES256_GCM,data:2WqWkYa+CtqGeca9m3yNrhZOHF4W70s5SBNWyGGGjs4YH1iM+LfrCBd6bAjg/HYqfqyN7I3ooM1qxs2qCf6wtw==,iv:CakkfwpR9TDupsfDdP7Tyjq0FJTeZ9vNAXb+7XgfMCY=,tag:gXdfyjX6X7qf3RP6h9RmeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZC9uanJLTnIrbHFWT3lu
            d1J6ankydjBZbWQ3dUNFbCtnNG11cWVYRlUwClgvZ1dNNTl6NDB1Y1NPaTBrbUVL
            RjlwaHdnQzJhSW1GdTNsU203RFkzcm8KLS0tIFY4Nk1RbVZWSlNrTy9LaWFaS2VM
            blBTeUV5VTRIZklZTHBwc0JKMTBzckkKDQ3QMQ1Zh7+9wOdY1Zo2/QqElRHZtKf8
            m2ZMdbZk19CxLB2DvyGqLTjKM1w2m8dikx4MQmB5vqd0zBaBYLoETw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T19:36:47Z"
    mac: ENC[AES256_GCM,data:/6VU1DRAWfOAJD4HTUhVpHKMPQpw9tDbRe94lwnTqPtsXmS8beXf4kApB9t18ozcDhxbGUszYPuDMhCk+GiNOe6vUf7ABMqXgToJk/Ecj6XN3z1o2FgqM8KkbTj0bHUpMXJmT8/BEmE2Qq7elvhUKNKqYbJC1hMSyRxSwG75ZwI=,iv:dywYLSpTOr1TJdoVzuMcOToX8dvrkV871fdoZpNR+eQ=,tag:dTw1QAy1jh+3CO6A1RJmJQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
