apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik-secrets
    namespace: authentik
spec:
    secretTemplates:
        - name: authentik-secrets
          stringData:
            #ENC[AES256_GCM,data:5wNkdy2iH3rd+6h/7+6yzC+rM2uENUmYgH20pR/9eLDyiKjOYv8D1pZ97doADef2Nh3z5YfmJ2iQkZMFe12rizTq41oL5zpFvkb8,iv:tOXQrOTINmP6MWdKHP+9FH5MKYSfCUa6MdBnIOeWztk=,tag:5KU37eIS3qRQZulFvATP8Q==,type:comment]
            #ENC[AES256_GCM,data:VpidXEIBHXFYo5llRgN0XjywZJj8cQEtRLIx65aTn3/XuZiIpg==,iv:1FIn4QLQXgXgWPNOwzs6AM/6gjBxAP4j48a0eqnUbW0=,tag:LMTGvKMH4KY3/JwUT3njww==,type:comment]
            AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:LNChWsjWc/8bIeGMbWpQuAwboqM/jhKQNF7e6Yadw7oKspIRvvCbxm9nsm5DTDxWHXsHAT/8WXjhe5xRdLtN2KfsXyqsKQU18HdRp3q71DU=,iv:Bt59is+eyOtVd4GoLgtIz1b6AFPR15Uc+Am3e2Qx9XM=,tag:Rqj0Vqy/sPhrtdg/1kbqFQ==,type:str]
            #ENC[AES256_GCM,data:MagJyiRA2wt742/FhVGfVQBB5UhYDbiroNT83cDB2mkb7F4g5QNV8m4vtBfwJyvhsnutjW7GAmqmAJ4=,iv:XDI0t80kJIXwbmoASH/Qbvy/DatQ/NvpwUlBgXMnN7s=,tag:HQ/ZBFNR/x0q4o1BCPdB6Q==,type:comment]
            AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:KnFeA5FDEZJi8eplqN5CWuYchQf863fl,iv:TvIe3b8H5zlV9Y9LvoMfPW66JtrozGKJDrsI6OZQ+zY=,tag:FWtKhEgnIFQYI2E+JKtCeA==,type:str]
            #ENC[AES256_GCM,data:uVDWOLaYl0Gi3nwUxR3xbOqTSak9y3gryjq0RiorNeLJFUxQ2M+a3DzX20cSSoD6BcKsLtxqug0mgMsk8R240BUdeJH52LxKZPnG2fs=,iv:q0GACrR8rBFgekNsWVZt/wCSIibM5djUCVtMrMb0HIc=,tag:cy8j72eznILZCxC96JVQ4w==,type:comment]
            AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:YZspj/bO3l0VUxc50bU3m16Dx/eM5jJPno6URrnQmOywKUewI0EHV6g+ulXo93uF9RMN9QzNGQz84tD5qxKwFg==,iv:7uwlMqjgXkOWNFJxQldEptNIHrFTECFvlNWtnGOpRWQ=,tag:7Huk6dx+GiZ3ltKxlteoqQ==,type:str]
            #ENC[AES256_GCM,data:v2o0n472tVoTFNxY5D+GYcL2yFVAbZGiZUcZbiy2MQWSCFgL2/HYWEhjvlh3whD2xwYd5uoN9fsWSZFe,iv:/2pBChraSDo8RgrCIbGghFXkZVfksagT6fo7vQjumJU=,tag:EG9Lm4dLMf+w2UUHuRPY3A==,type:comment]
            AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:Rq2xs8iKPndAHsKiy6nt99SUAKyFnp1FiFaP0bycS1UoCVd53lC1HLZQcLrWhBQ9,iv:jIuD2p8bgkrSlkvuGVQqsrqOBAw0NdlE6BOB85HCmUU=,tag:bMdPfUfuVsOcgmrRt86fNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTmxqV3BBRmVBTzJXS0hy
            UTUySmJNTkJRY3FPUDRib0tnVkRjaFd6VlZ3ClhXYU4wQmZJNG40Qzk1T3BOc3NF
            RGFyWWZLOGtaUG5Dd0NFUWk0aTRsdFEKLS0tIGxlUGdqck9rSVdINmdpWnd3TXZX
            QjlRRzRINVpLZmRTV1pkdFFCUnEwdEEK4swGBBHyWa8RFiG7cL0R5pTxqwkLKb8e
            eqBhrQ53nSKm6X6PHrxjKGNgga5gD3NtSFHkdLJOKVwJWsz+s5dOWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T22:25:13Z"
    mac: ENC[AES256_GCM,data:Bdr7SL7GXSXRny+u4KBNcooLwS6IdGZkbbAEo5iXy6vDTO1+Dy1h2wt+koCIz2A/ffzUc+Fsi2AVbaUvEqCwmmVtuMSRuW/SUumKXzXmh1C6u+aAg+/y3Mdb8fQuRTkI75DMb8iOXYDJH1gcBAofRlIE0k4SRnbToY8g4469d4o=,iv:YgSOVDhFUulmafOjymhYiKsOA2paQVGrtxbS/gKwdPw=,tag:SwUi6/mcwRo/MaMNtx/giQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
