apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: booklore-db
    namespace: booklore
spec:
    secretTemplates:
        - name: booklore-db
          stringData:
            DB_PASSWORD: ENC[AES256_GCM,data:ZYzfo1MJtkWyqfcq/tfMpU1eMCVqPhs0UOGpyozrFhbzgow3ATHEuWSBpLlQvhye,iv:MWOs3uCeF2tG4dscc/MwRr7uchsNYiNbuUPn7J5/2c8=,tag:SeIjn3RXgV8OYdRd7X7MDw==,type:str]
            MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:k6xf0OeUw857GAXErw4Oc9nDBTHFRjZTD0XNfnsSSEJosieB9LPthk2bQlL8pveS,iv:OMrBb7lQMkW2ZfAZ2IWmxp3L3NcmhjrueWpm4Fy834s=,tag:vH+2pAgfyoPWJ9nX+tBKsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTjYvT1lpTzh0WGVBVStl
            MGdoK2hvV2pkSGU2ekFHdWdFR3c4aG5uU0V3Ck5qTG81VTVKb0p2TVE1bThkVkNv
            anByRmFLa0JJanltOURDOUJQM2N1TmsKLS0tIHBicEN4SnJiVytudkxCYlQwOHNp
            U0plUzlua1o1M3dyYjNWV3JMcTlIQW8KiB7iVjM7g7r/2EWunn1odWVO3IpYNPat
            u9Ec9gHmVb12w6esZvSqAX7efOz2WFuvZNG3tozO5NbDfFcOiHSKWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T18:25:19Z"
    mac: ENC[AES256_GCM,data:W1yqMo2MZlHjo3EsItNrIsUJph17c4o1v+MNnIrotd/V6SHcInUZiFqFHN6XMWKmfrnsJiQY9Wef5wttCNXYjxFsrIMcsdDIzvll7Ta54h5v7CxJwI3D93Ee9S6HQwoTSozPgAP/J5im8sD8y6uH0ZeqRdua/WIAYvv8CABHEiA=,iv:U0fsrxYL2Mm9dbY0+6bnsKnb71impV3G/TugnJPakZ0=,tag:8+CRrRuVw60T7CZ3OQFEJw==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.0
