apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: calibre-web-oauth2-cookie
    namespace: calibre-web
spec:
    secretTemplates:
        - name: calibre-web-oauth2-cookie
          stringData:
            #ENC[AES256_GCM,data:IdjhgCdjyhC4sJYVtgDcSbsv1nqyiDH4fj8XhXsYdWEW0pIcRJFI7kv6qJqVl0Dvlkmm,iv:V6ZRK9aRQU4LgoiZQ2UR6psF5NYdyKWGylFAD+X2BGs=,tag:1lqHDgtIB+bTbPPuLLW2jg==,type:comment]
            #ENC[AES256_GCM,data:hl9aAiyQk5xmpURJzTAetkFH+DDJCVAWrtjSPHukEWYEsQU9MSMVxKkT5jFzj0r3zHxeb0czyHE2MZIm53SXErbTn+B9+ODJSlo=,iv:zvOnKvcijV/0BO/USQyI9ukalFqVAWJ+thaI50dMemQ=,tag:EVsG/7s5aKMQmNNRMky0pA==,type:comment]
            cookie-secret: ENC[AES256_GCM,data:d4wUcslMJWJi1LHw1SpMddubBTC9Ay1hB1APDRx93ww=,iv:5af7gmmUqYsCFrtrvKaOOZdjeuS4pAPRcROPn9Da1Ck=,tag:urLMp7YSuStcLxMHIBrOEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaFVoMHNkMDQ2Sm9CVmx1
            ZW5yY3UyRHB3Z2tQVDVNNXJXRE9OY1cyN1hFCktHc2RvV2JtOEx2dmVMZWZnS2p4
            VDJvVmU2bmUxRHhwaWFWQkJXOWJ2cnMKLS0tIElwR3J3REF6UGQ1eTdrUVNZeHRI
            dUpldWM0UHU4UUZwU1ZUY1lHVCtXNmsKR3Gcger2KBaKxKmAik+8WUeUEF4hEbGW
            p0mp8u8WV6kc2jcP6nt7RJ5pzw/EBHl9fB2cJHAAzeTgEq/at8Yb7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T16:21:59Z"
    mac: ENC[AES256_GCM,data:HrWCF/kw4x8mW6G+ZYUUiIAORoLZ936cWtRBAN83qeC80f6i7dgSjjUoWMyPmVGtmirUM+9cu+uZoFFSMnT1eItX8kkZYT+j33ItFu2MnV6hVyY+4FBp9+k2xSqrDlzeM3WmihGba0me+vHDpb3r7UjBxpcm4JCRS4bxviZTLvM=,iv:H4UD5rkqB/SX6YeyCAsQXx4lLqAuCD2jfMAy1fLYjzQ=,tag:ohOD2+x2VGlarT5fvjjWqg==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
