apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: filebrowser-admin
    namespace: filebrowser
spec:
    secretTemplates:
        - name: filebrowser-admin
          stringData:
            #ENC[AES256_GCM,data:9evRrMvMacDrR2stHtgwiRaKaQ4qOQjObH+wsD452vC0HxzcG8mu1NKUet3/Zd+cFcq6VmIQttPkA8Mmg3AB,iv:7sYuwHHqiXYz3+PxRZz1xG1bYVL/FPRf8NBYxmDb/54=,tag:4moHSXzNN8wuiGWt26CDGQ==,type:comment]
            #ENC[AES256_GCM,data:VUZLzbzjWz+J4wfJTCg3Uuhsnt53NN1HTl5ZGqMIme2dYYOpNzNXD5f1RWGdFcpI4q5GmKh5xtts4w==,iv:pcgNnVvGdLZItjdHODXvMwGMq5nDcXUI/5bGghRye7Q=,tag:bFgt6WoyNzCtmfGX9GxgzQ==,type:comment]
            #ENC[AES256_GCM,data:xy+7oK6sVlwIAOxqtYicOAq9B0ulCXx+YrFAyeh5uANO24fEH5vdy5ZmajkwcubkL2ct8Fh+86zDYUtKKA==,iv:59rnemY1w2f7GYPeqUKv+X92w/UNxn36U4u+pzbjBH4=,tag:mj7x5MB2UH6Lj4IkmbagZw==,type:comment]
            #ENC[AES256_GCM,data:4GSWgva3c75xG3TNGmwETB8mAuWttn3HrGCprxHTroY+y7L5RKi5fdpiWCnPbMvdspkZwQ==,iv:+BumciM/6p+xSanwX0RVJ17SVJlrUq8BxKnKL7BTAaA=,tag:YpSLTz1SMg9MnaKVK9QTUQ==,type:comment]
            admin_password: ENC[AES256_GCM,data:6OR7GsXpsTpfMvJZNl+FkfrCKbFsm6Nw7Oc0t3UuFhHA9WwKtsXgb2nVTgv7+k4v,iv:V/g7VlJ6FVQiJC+kV8lovF4SOY43DYnL/p4+IQ8LTjU=,tag:Mx0M4D/1dDow4VicxH9UgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WVBxK2hHeE5WQnZQOWhD
            L3NPQjlWRDNDeTBJYmNqci8vamhTdUR6WTJrCjErSG44YXBDeVNEQW14eUZiNnBl
            SjBobERvbWNJeEZneFgyNGhMbUI1UzgKLS0tIGE5RUlkS0VQR0g1bThuWkozSTd6
            S040NUhiQ2pIMndCQ1AzcEJOd0hzekUKx5QlL920H1FneYJGshmpAmLbyhTYU5Dx
            M5JgPVddC2gXDoqVIG/BZPHpHDeXWKcQcIw91t60prGo167K869dMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T17:38:36Z"
    mac: ENC[AES256_GCM,data:PEqecjXGmZ93UJ2CeHv7IC/Z/LBqhNwjK72qnweIwXvp/nOSofGFx4dpv9Pb0x2qeOPMa73y/L72MBJN6F+twmZ9n8kLnxc7WM8o200+Db0wmlmKPsEnvcevRy1OqBEixqSnKgVUXH88ZgpP8qfHTS5y1up4Ba0SnU+J+9d9v/0=,iv:I9vFyoJGCUB97auQNNfWJeDH830mSWr9e3vZnVbf5Cw=,tag:Em6Al2nbdx+S+14DJRGpTA==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.0
