apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: forgejo-db
    namespace: forgejo
spec:
    secretTemplates:
        - name: forgejo-db
          stringData:
            POSTGRES_USER: ENC[AES256_GCM,data:MIDifQCOtQ==,iv:psMwlRwCIrTYGthBr7Av/+vC08TO+lXQXmkrcNpv/w8=,tag:7z8VunX0X5Qxr/7e4J8dDw==,type:str]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:Ezn8FS9twOHn2HCb/gRjVGF1X42zNP1F+nNAODOwWXWoZSY1gfWOfeHNpoQ=,iv:0DyEOBT36weu/DbpEJYV6zEtFUmwdWMvge4BXB6i0Io=,tag:cZkvi4jWWTBox+o6NHqCTw==,type:str]
            POSTGRES_DB: ENC[AES256_GCM,data:QxTLiWTU1A==,iv:DKlF+B9oN3fbwDigeG3XpWcLalLUZF6O7KF9L4MOEzU=,tag:4tYEeBzZUjSdvTVyZTHIvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSa1NNK3ZMUUhKVUx3Z1dt
            c1A1OE5HZ1ltc1ptMDRIVUI0YzY5a3ZRTGxzCnY3dEJENzBEK2pJeU5QN1NzVHVu
            YlJ3a3pqVTFIVUJtc0M1TkpJZlRUSXcKLS0tIFh3SjN4SzBWWnpIZno5RUhRQWVy
            UUV6UktPc1VGeHdCSFJNSDNob1lJRVEK79MdwrrC7R4pFKKceCupXO/YEcQVgKCd
            Yupqjq6KZRR84xUP5OfvJ6JmY3AcLmLWMPi9fyjQbZxUpquWabMewg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T18:31:32Z"
    mac: ENC[AES256_GCM,data:UINw+IUrC9jbBPU346sKW7oazlgB3q97UtEaOQALwljJPzJpwe0fCv3CQnSYrrz9lst+Ij7T6bFArbvhAqNTDHlKgOYbEpxuaDyr6HIFD6NegI1962LdjXUXQl+wyFYrltmzbr4qpLdOyrNwFlYeRcj2vXUvI9/wDLRM+dxQPu0=,iv:bAjyGT40AiP+0DQUhbxEi4jBp3s9TgSWH87pratkg+E=,tag:fJB6sqFQulGRl3hhWFAinA==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.0
