apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: homeassistant-openid
    namespace: homeassistant
spec:
    secretTemplates:
        - name: homeassistant-openid
          stringData:
            client_id: ENC[AES256_GCM,data:jYvGVGEaQBEzzhuLX3T2WkvSIggL9zzNtojN+W5Anapu8+gS7IpXhhsQ2T67kboqDaUx79asipy7UyTcEhmfdg==,iv:Ox/eBzlW1fBcBDHGzIPPmRlUwgWmRE5FrD92G0CXHhw=,tag:SzIt0/gqXt9UjfaJrhbhcw==,type:str]
            client_secret: ENC[AES256_GCM,data:XFPhCKHqcOweTNW7OLnQq5hr1zSGtnFBgc9N8RbapHZuBaQ9h+piJx4Fh5QkvTWYpcgmrMeSj58EV+WjWh8gjQ==,iv:i0CyXUvICtc8gX1BmmueYAYzrRz1WtqBKzzHZwYjNRo=,tag:YgNe/kOY62WSgnwaAWtYQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZGFjazFSQ3ZYMFhiU2Jm
            V01kc29nSjFYeEF2bGxjYUdRZjArWFk4L0J3CmNLZmlMYlRZa0g1TXRqMTk0N2JH
            WTFZcWdyNzg0OW5XeW5ENHJKTGZ4bnMKLS0tIE5CeTZpSk5YOTJRNy9KMDhCYnJL
            bW1oYTkyd1V0SEpUcitmZHNiRGpWbDQKqd4qNPXf3MJVzKaXyoUeuRpyvti/wGxn
            qi7OnHWbB0wcSP1oIPhPlRU4UuqN2b5gEWq7kYeuhbaL7I0ajTkymw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T19:39:36Z"
    mac: ENC[AES256_GCM,data:3hVeWS0Pqx2oTihFDcFYBVIsDdKuRz+AAlI6EsWqF9F9bT6I9H3gMlGC4yZ/qJ8jJCZbAg0j6IsQ4L0D5+E4lBERGYlV3MbY7SZidNlwSHbCm07EnW7MTh5JjItsrkz52A8rzUAFLiWmRyV5HFJTU7+6HC9HuYfqoTl1Jcc66lo=,iv:GhF4vEtgWwSL2VUXm6wHpW2TOsCtEy1nL8fcbwfYPbg=,tag:sCYkyM5Z82taoq376Kik3Q==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
