apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: home-assistant-oauth2-cookie
    namespace: home-assistant
spec:
    secretTemplates:
        - name: home-assistant-oauth2-cookie
          stringData:
            cookie-secret: ENC[AES256_GCM,data:ucXIfnbawWVQuKyod8TpOWRnUjnJfPW+k7iG3eMhj11vKgXGvSvifMSRd6s=,iv:WqvAg4nOK2pKueVOIvR7Hzm5IV0Hz73goCjm7SGogPI=,tag:P49rmemrLSZjkeWIczibGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAza0NvdDNUZmhWK05mS3NO
            K1hxbmRnM003NHhHdTJUTnFaSEVHVDVrS0hFCkNnN3YzY1hpYmRROTdXNlBJeUNh
            djZQUUhmUXdyaU8yOUZZWXhrdXJKcVkKLS0tIFB3R0h3Z1lNRWpxSW9Vd1dlRGUx
            TlZmN3FCWlQ1L2dWcEJURjhiSGtIL2MKacKLCX5mcvjgbEwriTAhQxROeBCxYa9e
            etrpsbRxhG6yoaaFZZzBWlvNORWDP5lfwdxOvM36WVH7XrKc6qlXDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T09:17:24Z"
    mac: ENC[AES256_GCM,data:0YCnvK0rpVWYx4EeU39QbSruC+BzjXlEQMMrOXQrg3MxartdvHZvUVvXcxp8Kv3j0Dc8kC/QiwX2gZKn016Q79HDrrgpfrpV8meZchfXnVGq5XHbgpGAxmqlay52mOZ2b6ixMiclWLygaul9rjrcYSbPDBfmhqBsIP97IHq+97U=,iv:NukPDMptrsKXFhP1VWxmS1dC3tRrcrXllFqBBGNNkKI=,tag:ZAq6NKzqT5DqrIV7V2FhGw==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
