apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: home-assistant-oauth2-cookie
    namespace: home-assistant
spec:
    secretTemplates:
        - name: home-assistant-oauth2-cookie
          stringData:
            cookie-secret: ENC[AES256_GCM,data:cO9y71edAtt6RBCreMN358qQyfiT8AFhmZbBySfJb04=,iv:TgtVCYf9XNNYBmlOhr2FfHJiZG5jC648UUbcbGXXOsE=,tag:HOjVxHEW92++ate5TFYRfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZ2lyYXBTZzYxdkxQODdu
            QnRBNjVGN0t5aGQ1VkxKaFpFSFB3MjNXNUVNCkZqSU1sa3ptQndpenlLKzhYczRO
            MktTM0NvVDVUM2JMRWdnU0VKb1NJSXMKLS0tIHovMko2c3RFVU0rRC84UDJwVjZ1
            dWFvTTZTc3NLSjBtU0k1bi9QVm8rZWMKbZ5I+J9BEz1oEyppocal1UT1N7h8dBwO
            6fz7sJQvSfcMyDdKRmyi8xqmxolNcfAygiQ0abshuHZC3tn4Ldw4Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T09:36:30Z"
    mac: ENC[AES256_GCM,data:sQPPOj2DsEFuU95d2Q4p/XgVdGo3CNy7/WyAhZAJ1f2KKYQf3YInHR+dEHTBeTuA3UonXI2YnwrlSIhzAB1815ojp46JmBT3xKOv17iadHIJG1I4r24UhQF279h6H5XcNeYU4mvsl8GlHcwH0jmyxMQNrO81iF0ZQ2nRGG+Niig=,iv:k/3GrEEpxn3b+p2PX+O2FDVh2aubJd/2ENT+HeqPPMw=,tag:KYG1D/giS8ebwBkWFNXPlg==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
