apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: jellyfin-oauth2-cookie
    namespace: jellyfin
spec:
    secretTemplates:
        - name: jellyfin-oauth2-cookie
          stringData:
            cookie-secret: ENC[AES256_GCM,data:iWIYGJPA2oSfKghVioKm9wzJawVmN4LnEPHTVCR/ub4=,iv:u/i0e3RWw/LMAiBhRmVs25qA3IE+0Ms9fdQIFE9zlwA=,tag:PfMzEbi5+FA1Qqf4iOE9dQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbGcwamNXT2VhTDZ0akZW
            MEdyNUhMbnVRSktFTTRxRUpsbjR6ajFxNlRjCm9DTlB5VGpQTEo4SWQxdFU0Q2Nk
            Q3RvTzRpcUEyaXJ1aU5zTS9sV2tLRHcKLS0tICt4a3owU3pOWkZrQXd6Rjdvc1pw
            WG12ZHQ0S09vR3FaSGp5c05PM2RtbVkKJcsZGNUEKmbmXIkXX6Y61HxpOvWABCvh
            MDyU5Ubslizb88SWgwQJOONkZDAolbDDNNT/KGDrwTOXB333D6MW6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T10:17:43Z"
    mac: ENC[AES256_GCM,data:tM+gQaomLVabyWgmvlzsj414dQfQpJgDzfsp4avEebEfPCXYEecOIJ3QdO4P37bqQTzZ28WLGZp+1BtvK1E5X9i5kJsUlj46MqiJAQW2MVSdZl79+CsTMS+vM1YcQ84/as3/s8bkroJheCc4/cc4HW/sVDyIhOGN8B07frHFo4w=,iv:k7jUQPvlwhi1PDvJNxupF5RUTAv8z/2VaiQPMbCdktA=,tag:PP3FnVcgxadL5G2gUYog0w==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
