apiVersion: ENC[AES256_GCM,data:d0y4688OmjT/L4zNGAQW2sKREFE5OZO92hzY,iv:fKju8+YiUXNfG4++w3LDgshxIrP3dqeifHxBJv+AagE=,tag:HGJ0j+NtWO7aaCsbY7m0Mw==,type:str]
kind: ENC[AES256_GCM,data:tETVd7gTZDC2cw==,iv:FvfF92RONzZ/i4bEKul+OpK3OZqfhkagodkVbwtqBxc=,tag:iFUQ9clOfSkuoc5kBj/+mg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AWE9mJBM/J+9bY4slaqo0/1f,iv:9Ex1RjyWi+eB1TL3l9/oTuFzvQdjJhbSmLHwRMJHbGY=,tag:vRRZXggned4STjQHDaY3QA==,type:str]
    namespace: ENC[AES256_GCM,data:aszbJeH2NOqzQQ==,iv:YijlYZHWLpfd5McHmMeeVM7x5qsju9HKmHtx5Rpjv1w=,tag:z3kSLai8Vi3o8pKCodxJtQ==,type:str]
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:nB0uppzAgBQAuWkBR5wASVNW,iv:J6O7wJEKF+sOMEib+Q58IUAiQTyE3b78VOO+ee2qpLc=,tag:b0mAeL3XiSRs/8eXdQup8g==,type:str]
          stringData:
            personal-number: ENC[AES256_GCM,data:wyxPsLua0CY6TgQE,iv:ZUD/D0dJdW3mE2oSazrVphmpuvG0sjjedtDKSJrHTXQ=,tag:NDXQVhCRL8MXlBueiLFfgg==,type:int]
        - name: ENC[AES256_GCM,data:NrIATLQxK2k5UDwWIivNJXgRsbmMV9zgug==,iv:xVFDoZ3H4dIEjXtlstMIizKREie0INvE4c4Lilcq8/8=,tag:eRCk1k1bXfI1A5RD4SEmiA==,type:str]
          stringData:
            cookie-secret: ENC[AES256_GCM,data:5rtt0Bnl8FHHa0m3QJ58qIxYhFRQqsKqN+O1pDJvCi+Zva7urytfKYabVg==,iv:pJPhHFWfjGHMlFKxFRj18GyBUlE4YrMeOwACvQy/hok=,tag:pjLBjRDRNnvyNuGi00N0uQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjNiOGJuRFlDbkEyY2dZ
            dHJOeUFFWlNjOHkrY012dGJtaktmYzZ4T0VZCkhUR002SmV4bG5HbFJIL0o2MzZR
            VjEvWmlsYmh5R3E2Unp6VmV2aHM1bDAKLS0tIGVwZnNwYW9DLzRVWnZtN1BVaTF4
            L2c5bVNnVnIrY2VmaUJ6cE83WWVUY00KOT/HMyM4nJQqUyB2ROwhVPf9oguxE90j
            RpupLoD0losbvpURn6FRZsPGF3Sc7ezX/4u2wl1Ud8T+ZeyREFEe5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T15:23:19Z"
    mac: ENC[AES256_GCM,data:lRUaRRKZM9IiwpQOvBGckEwfF+sW/Ri1g+Bl3xIs3ZwTIBSyDSXbSnLJqlZ+y2sQWikW8JEKwztYl4hOJGJgGnkulJKaW0zAZRj8RGg7Xe2mu57feVx87BXw3jn6p+Vnaaswbo5BZHyCZdB6NQ8Kwq84HzqoqXQ1zEOvGn7hP8M=,iv:FqztINrb2FTC7xCo+CbxLU9JA+T6MSTwf56LAyZwdE0=,tag:BjO4Qjyy71s/YRVQlxbOxQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
