apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: kivra-sync-secrets
    namespace: kivra-sync
spec:
    secretTemplates:
        - name: kivra-sync-secrets
          stringData:
            personal-number: ENC[AES256_GCM,data:KSLZMq6PDWf2TjMC,iv:lqhKrVVa+vRRAaiqlQdg36ZhvQchNhpTwkreTUrVRN8=,tag:LQHeFWFxSZM9AMD7O9e5Dg==,type:int]
        - name: kivra-sync-oauth2-secrets
          stringData:
            cookie-secret: ENC[AES256_GCM,data:/eN8cgSEWD+C9MtFU1wjCFX5IPMUG/7hLVI093bi3iFh0fU5BCOlnltlHQ==,iv:Ib8ovxprJ2j9v1A1HMCbOjDaMdQI+szZEFvftRKNr8g=,tag:o9bT5tFgGm30W5WlI3RzEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQTdjeDR2KzI1YTdMamdo
            VlFTNzg0Q0xQSEdxYUVvaENhZ0U5QWp4K1VRClJPbjBEelY0WE1BOWw4QUdCOXJw
            OWQ5cFRianVGUnZRWWZLWStrU29kN2MKLS0tIG40ditPTDVCSE1OTlRlUk9SZGpB
            YlQ4VEtMZ0ZJNC9MYmV6ZzJOV283ZzgKsnBlrhXbmhyocou3kDfKVV7UZtblp0iF
            0/J5q+Gr2ufnpEqZfvpo3HkTchVAYSGhevXagQF96ju+idE4j30oXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T15:35:06Z"
    mac: ENC[AES256_GCM,data:XPDXcKUQNNM9frjRdmyIQDVgzFC7YDuMLIZ+dl/69V24XMtgqsNKP+Lo+jQw6pnoaw8Z7UiGagYqHCr0saElZQUsySrbrH9gQM7g6ughyMGfY98cXOwfLB+D5eFu+AqTRXk0tdawTjDlwB1V7JGwGk0LK8n/yvrhgbqywqMQvgY=,iv:DTIQMk12pexrEfqVHsTcWJnK6gHZ1+gAEB5wYqCoskI=,tag:J0a16tcAqsxUesEkM72AJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
