apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: metube-oauth2-cookie
    namespace: metube
spec:
    secretTemplates:
        - name: metube-oauth2-cookie
          stringData:
            cookie-secret: ENC[AES256_GCM,data:IJDdb/mRMLkp8ICqbcSBtQKxapnEL26S6CzKG4Qk4yw=,iv:iNID10nTBCeOu5iiKPC+RuqsKMHaA37Cjlr56Gy3Xwc=,tag:tn0yK6oquy/pYILnmAQQNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjU0daa1hlZ3YzUEhrcjV3
            VGRobExVWjIySUEvbHBDZmd2bXVhK3ZQM0JFCmpUdzRJTHRIS3BmRFU0d0NEYy9O
            UXlQZHQ0aEMyOUVLUkthWXlLTmcxRG8KLS0tIEpIdEJlbWRteEtKV05tTThMUWcr
            VnR1bG50NkY3c0FYb2VWbitaRWtmSVEKbDmjLvXXy+8J4GdNeI89bpOSjni74HnI
            sm87RYHVQckhJQghpj/mvSfKO+6tHH5AxjURCLk7Aeui35va6Jpv7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T10:13:00Z"
    mac: ENC[AES256_GCM,data:UM+jzACkwn+9fXqMUN8G6ndxNYjZyJB1O8VUrGqzA840JwCB5abN5EeW/kSbOxy0Azb0q2QagfNaPNTetRsRsUOQxXrVGL8tmCXkCWwHdh4mAKTo8wVFwo2N7EmFVWTkr7HKXvkRU2xHOjfXZt4VTzSWIf2SuA9plEyYO5MwcnQ=,iv:0zelUzvcqpQLtU1XPn/Y1l0VNKtqZXom8YmCHHqi/9g=,tag:BaKce3mcsUIQfwEmoJCCWQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
