apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mullvad-wireguard
    namespace: qbittorrent
spec:
    secretTemplates:
        - name: mullvad-wireguard
          stringData:
            #ENC[AES256_GCM,data:uNhosxZXeLW+6U6B2SXIMH/UuTrguxh0Op46bTJic2nVzayBxFJiGkF8GqjN4ds1NH/AN2sIe3Uo3y8TTOw=,iv:tCiNlPktvrb3Ium8nh9o37IEiVJjvCF/u3FYynIfDOs=,tag:ydHhOlxvtS/crVquVxQ6XA==,type:comment]
            #ENC[AES256_GCM,data:ZNzr3q4+0TU8X77MGLzR6RW0tXupeX18UuxgJApy0wSUNJiyMIaWVTVf44zXhpjSuKOOmaB7HaSge+3yNrA=,iv:7dJhfUJs5B+40FIHp04+QWyh7YJmJ+zA7oSv5BQDfB4=,tag:IEuZKYDJUNOr6jLvXS+GfA==,type:comment]
            #ENC[AES256_GCM,data:iKFt8F0omqrH62WwdP9vXBYNeDQPjq+jykxM1SjIC34tNCy9dzLF17Du0/vVn7istreZF9xm8zUE,iv:CyZelMSfsh0PAng/R4jcrahU0H28vO9RfoCnWomhErc=,tag:pQQt/3DdSbKOKItsXnB0pQ==,type:comment]
            #
            #ENC[AES256_GCM,data:V5LP74/zABo73BoQcLyAzkucfmMktYhjKAZ3agYfDDkV1z0tv34AC/lYzu/maw/r+icxz8GPU4xqAnVdnK2Fy/Ypbdr6jSDX7g==,iv:3wn8YQau3gSt6J4v4UDjj5x0KuizdCwuY6sjjRIUm98=,tag:38z2KXyClAsT1p3mm5hxgw==,type:comment]
            #ENC[AES256_GCM,data:UwZiLfDSZFlo4P0oHvK6Gq4L0kUbXW8HEneKQW69RsPIpOMciTPN3zIRAD1HB1FFu0WPNAz2zQfahxLQhSPeXw==,iv:2C9N9uL4z4TifN0rREWc+N0c3HxDoRfk4bVDyL2BDxM=,tag:kJLzWy0E1u9IBmu+na8dEw==,type:comment]
            #ENC[AES256_GCM,data:h0RLt6zIwiTxxRae1IsHwxafZ08M7l2T2LlbZVi75NsQY2qQybbWYpx88d5Xuk6nsukAYHRRPpr4qAW6MQ==,iv:n9EoTATJurK6ZKga9NxbEGLp16H7HAe+IKVhjlVaZi0=,tag:FR4UeoXHCPaKwgDtSohHag==,type:comment]
            WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ennQiiCHSoOGCw==,iv:babQVAyYkQWs4iVhKTebY1zQrUX90Qr72KMT1wW5s9k=,tag:1ioxa7LJSSBPZb5LE3XLHQ==,type:str]
            WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:gEpfehO2yBvaXQ==,iv:ic3+VnA53a/FcVLFhuSSe2Zp3IIzJBnbu4aHQ/DQgJE=,tag:Co2x7Mhrem9y/sZTiNnN4Q==,type:str]
            WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:HW7Cid6ihFliTw==,iv:wePigLtHFPSvL2DEBxCnMubihPdmIrofbmRpW3UONlo=,tag:N2F67ETWuv44P0pZ64o0SQ==,type:str]
            WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:FNBDGqkPnI+L3Q==,iv:jikK5YcQT7NLBl09fMa9jsjCg5ZUQrFWSXD76HSvI7w=,tag:M8rEMQBs6acDqApwPxPXgw==,type:str]
            WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:gb0u6gY=,iv:xHpr4DK1Qdsr17IXxzimthumdjFbZNsRqzeklOgvRn0=,tag:4W65WQvV6bq171oCRw0hLg==,type:str]
            WIREGUARD_PRESHARED_KEY: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpT2Ivd1hXeVp6STZQNHpi
            YkJLUEUwaklqYUhhbFhCTTN1ZUxPMzFTMTFNCmxiOER3ZG9GRzJ2RWxDWGUzRGF4
            bXA4YkJtb3hnZTdDK25MTDdrNWMvK1UKLS0tIDdyTzJrOG1KNTlGR2hRY0pRaERz
            V01LWnZKNEpHTm1RNks0VEVaUUsyYTAKVz7zXWL4B5VaKraPbEl1czJ6NJtBcYHk
            GAsTa2MAxoJKEF1VYWYaurOYgJ7TN8bhNX0kRKDfpowaIXQF70Dr5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T20:46:45Z"
    mac: ENC[AES256_GCM,data:Iu+/bAk+vlWYDVKtLpuMTQL9vvhO9tKFUIR4HqFrb9DZ3d0gtBaoC7ioDvNpaNfB4uNFFqqUIUTUCkc1Vq5yujU1EV22DPYCZfjIm7fyHL7vTAeDUVAGhZG/Cy9C2ll1xxzdCxUFzZq5Q8fEZYCn6wqgQpAl0A+If315DtcCRs4=,iv:JIYvhs4QbjwcxdKa7zLQRJzngFAg5WwUj2gwwRoJlnE=,tag:m+nKXhxTeekVlaOU2Wc4jQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
