apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: paperless-ngx-secrets
    namespace: paperless-ngx
spec:
    secretTemplates:
        - name: paperless-ngx-secrets
          stringData:
            PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:R+1PGfeZK7n9aDL/efQlqXvFCW4P/gtHld8gEyJcELgJlVNp+8+1ucs0oTmjbM83PjMYfJS+gfZebqEJ4clJDg==,iv:X+Fyy+Mq7JvTMoaJ7FnlDIB4qXiskHycpCIKjp1diVQ=,tag:4PoQKfr/PevefBPuQZ5YfQ==,type:str]
            PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:85w/s7E=,iv:3Oue1RtMovhbdTvfCPVCcVzoG+EA9pmAuGrA3joD6ng=,tag:25ZpWe1nE0Ze4R355GwDaA==,type:str]
            PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:Nrhyb4sX4RHoBGfeZGpOpK5/UMnvirli,iv:5ynUQdbEe6TEPJzw/H0JVzK7+PsJkhN8aokW3IxCZY0=,tag:hn/tysf6553duCYxyMv7Iw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSDBrZmVFaldqT1VJMElY
            TWJBOFN2dUhGTVl1ZHdYZW5oQXBKZDAyYWp3CnFWWGpDdUFXTlJLUUk1bFpKbERu
            MGhDL1l0VVkzS2h2dUNjMjNGRFJONWMKLS0tIGdRQnFDbE1WazY4Y3lxTkhqVzZp
            cXJpdzRqak1URm9FK0YvWUNiZnBXNUkKspDn7b7T5RIOBPe96xURqYcp1LGYClGy
            UWHpAsFKoRrBxynhTrpi1wCuOrRoXXf96EWSqhFxJW2/jsjWnohlZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T19:39:32Z"
    mac: ENC[AES256_GCM,data:a8Y3hNQ1Cq/9FSxOSiG8agRCySp1c8Sb+c+RbecwphjwKYQHYvVfxV+HiAoN9x9riNjotED+pdtwZiDbl9LTMZv1+3dclkZ0Jx8ZrI7uhzmUmKDqE/w3Tw4zPkbTajBdFJ9HaJA2+wjQEnFg3whHjftsP96WYpyppcaObBrevc0=,iv:i6Bf+Vrel7ttSkmNXF6rew9+YC22uoo7uJvQvb1pgQY=,tag:BM7a6sfYl5oAzKXNwc2B3w==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
