apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pocket-id-api-token
    namespace: pocket-id
spec:
    secretTemplates:
        - name: pocket-id-api-token
          stringData:
            POCKET_ID_API_TOKEN: ENC[AES256_GCM,data:sfmBIxR3bKBckg==,iv:xtfvbwfRU8Hf2fB2hNgC+7DGvc+WftQ7mTlxfbQIWSI=,tag:QTbixhUqCUL1ClO45fyq8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMHNVSjZ1VWRDd2l2a2o4
            RUs0dnZGL2xFVE5odTl5TExFTTlnN3o3cGhZCnRXbHNCNlRzdk16UmdhcnFpa2xh
            aW0rN0FRcU1RVEh0TnBQQndxSTBjeTAKLS0tIHhzNTB2QlRSSU5WSHNPQStTRmVE
            YmxrWVF4MS9zNEF1OVhXNzZ1SkZuWkUKKr/KQkUdDgGyrX9nidkXVDLEPgI12s1a
            /CJzFWmCDTmesh2goLwcfNTJgZhJ+sZ/P2dNAu35LZjBkk8Iw+y43Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T20:40:57Z"
    mac: ENC[AES256_GCM,data:2s/tYGDu2p+oZ9oGtrMU02YePBXcEsdw0Rsfnp6mv3EiBbRattTp6SGn/IVOFRMOW9agbW1Wqwqr7XqhMIapk5FKA6QwVGqq9VCPbV+O8giM/TCcOpUfqWFTDQHOMaasnTNO9HkUIPiAXAl5i8Uns8bV5YfF+F1B5yiAyiRaFcc=,iv:f/QFbdIUTRnDlM4DcR/CfM3oOC58wqOWHldF4b/11SE=,tag:HPZCg1bM00cBLxtzNJi+Ug==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
