apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: podsync-oauth2-cookie
    namespace: podsync
spec:
    secretTemplates:
        - name: podsync-oauth2-cookie
          stringData:
            cookie-secret: ENC[AES256_GCM,data:I+CvW9NrZspa71HXf8t+lkHprOJk7Bs6BM8nanoCRrQ=,iv:5eWMuhCKcQBYNwTqzn8kf1siNr/WnC1chYp2iHD4xUs=,tag:zlLFXCaxrAqO2kLHdpSecw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzR29DRHk5ODYrNWMyL3FE
            anBVUzliQTRqczFzZzVDUGVtMENzYzlVVkRvCkRzN256TzBpSlBJZDZWRzhEOEVR
            UlRhdDlCOVV6U1hiNWx3T0l4TjNzNFkKLS0tIEd6K0NQMXFtSWV4QlRuYS96N1Jx
            b0crM1hXeDAwd0lUR2dDVzdqQkxOeVUKgyuhZtrEnSPAlkqe/QVQLqSOqBi4cvhm
            ON6o5pKNFt8um2breJVngMMGFCGe4H5KwTSBCzQNPsLd4pLxVkuIBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T18:27:15Z"
    mac: ENC[AES256_GCM,data:rqHEX3FFoEsZzI4sNUuQNP/m1riyFrcu6KGIllvnON89+bmC++wxzvdAiR6/zXw9YTq+0fOpEgO+izxDnZ13jZScD2lht28r7Xu3OI6ogB4XbN/uhEBLGJwxkpl6mrEBJq2zgrNrPilxn23cnaE6Dk/Xd53oGHUCLFvCXJuCDlU=,iv:Jqy2JL23M7mpe53RM6AF6nwRqwQeOLGwf7K6UkFim0U=,tag:IZI7Pn56mYZ7bmNOzcWlEw==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.0
