apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: podsync-cookies
    namespace: podsync
spec:
    secretTemplates:
        - name: podsync-cookies
          stringData:
            #ENC[AES256_GCM,data:LhFp28lejcUtJJj+NSxd92qLD6iGMBWDPoelGSESm4ZPjqPKSJ0m51x0YWDCnsV0Bi1GF6tvTs+pJuTKKSABelOqHIHgu3Ta6w==,iv:+4w5Z+VxByh6PxR8J5vHjmx9jgSiYdRKhAwPpHjOIXI=,tag:HUhYOiJHtEEbAsFpM5RqZQ==,type:comment]
            #ENC[AES256_GCM,data:7kv2P5wW/7pmGtNhnSeBoxJ14+HqRL9iY8Uy13CJEVHXNVXVF8njiErCY46kRuUzZrZRcvvgGsV6UZu2MOTxoCFm6kw=,iv:WSGi1fXoLxYMp1HfUb3q895dOn15MK2L57FXAYvJTM8=,tag:/DWfV3lpW3ZZNZSozCPeIg==,type:comment]
            #ENC[AES256_GCM,data:zesrWYHzpyVCjoHT2DINy/3jRXImUVv1fHjs1n5iyQBC9htkT/eIamWQxtvogQ/m5Q==,iv:sndDom5EjWvxd462xK/+8UDgkGkLhO5bs6TrfAKPI8o=,tag:7jGxnEuWXGTTk6N7K6X5Eg==,type:comment]
            #ENC[AES256_GCM,data:alAHBvJQS7bqgi3JE7GEgp77IlBYFMGirlyd9+bW1Xck+QggXvyDPLrEONghin6pdaoiVQ==,iv:9xBU9I6UNDaWxQIQ1EOGnvPh2KcVmaQFWgQqlbPCrME=,tag:XfDCDGbWODho0uOm4JwIlQ==,type:comment]
            #
            #ENC[AES256_GCM,data:C5Kn+q97GHU6iqNkwpmFR1ZeoGbxqMPuPGa+boiIGNwtEv7Grpsq0ErUY/efiCgMkdcCubmLF8Ooqj8IPlxW+94ong==,iv:BjSj+z4IF4DYcZnNaGfrTfW/qpmnHAW547H+qzexvMw=,tag:aH9mZuHbYcsYSZxlwnq7PQ==,type:comment]
            #ENC[AES256_GCM,data:/3Rxx0qVjjXhVThrT4VwTJQ4t53ZewPReTDMGLkbZ1kSfxWP6uZkoNNgJXlVCSHrj/qieVj5lR+iyIZeOETFJDiUsMPx,iv:WiLQHKf+C0PBuoWzyg3uJn3fmR/DiV6u9v8nwkdxP4o=,tag:OvzI21pX26/oZGo0G6YfHw==,type:comment]
            #ENC[AES256_GCM,data:gG9ybQneeGyjE80tE9/FpskP8m/OOWk9IZtdHRRaYugLcGBlAk/XTzroJ7hmX9kTyhmkQHy9OVf+TBF4O4VCO5GrQw==,iv:J/vdAYKWdogw/X9YqtLKwMu8MCf3Mg9V15X6wl/VUdg=,tag:Kgf4JgKItRYHUJtiz0sckQ==,type:comment]
            cookies.txt: ENC[AES256_GCM,data:P10QEFqkMfq5jitJYCFKeZx46o2b9dZNynQI/hOPBdKAxdwDVxpU4Y9T9tgAhRw+N1vbJJQKGA+6JYP3yUr5M1S02H3MgkN6BN6LyRbSh9bknsTkCT40k05C/A==,iv:NHuUay+LxJPq6aQyqHUyPkt3Fny/A1PeRyVPa8huqZY=,tag:n4qXKWrW7vdrzORzxDOaEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUmswM2lwbEVnM3hQVDlZ
            NnZuK2JkT2ZCNG9yWEZvajY4YnpjaUE2Wld3CmptV1dSVDVWMDBtWVhQcWdlY2Qz
            bTFNTC83aGFpUHNXN2ExZSt0Smd5ck0KLS0tIHJPYkwxeVFaeTEzSzhWNXpnTWFR
            dURndU1HSU1jRGFPTlp3L3h3R1BvME0Ku4+CQ3DoZP2Stl6iFrb/u8zB4i51f+sS
            4JeVussLcbv/628IZdCnzTRoOT0gtEiI5E6wW0LY2y9XKCQqMqszvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T18:27:27Z"
    mac: ENC[AES256_GCM,data:ffzBdb1SxYkkM+D5uD2JUuLEjbthjMhDkZgjf4I7bmtNO0maobIY7kaNEnLLLaR/afUT+bFnyVuIIAmCcED4u77aICTt+PWFLIpB0cpDwWwPMYGMErqUnxG3Xx3mr2V1ndABsN4YKx66+MjqifPpBSIaFtek6vAYUr1ATQrJMuc=,iv:hU1ZuQAjaHclpnvrpqo+4Tw930f6UWiSLQgx5+MI1YU=,tag:gYtmIuqdLum06g3Bus1qmQ==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.0
