apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: samba-config
    namespace: filebrowser
spec:
    secretTemplates:
        - name: samba-config
          stringData:
            #ENC[AES256_GCM,data:7D6vWhc0Q4Yjsve9s2++H08VFupAkYiQE06AIgEoZA/2MF1GLfP/rcgCWpVneTJHn/ZCxSq+67AZemVe/Ny2e8M=,iv:7r/nnoxunfLrG7aC7UHifQhqQqb0DAulACBle4Kyhpg=,tag:oGiw7qlm/JVTzLwS+KuL9g==,type:comment]
            #ENC[AES256_GCM,data:1fB3AiF+n2deo0kv8S3BBUySWgwnhDqO+8oYh3DSsCiLEFyWQhoc+Hr245GI4SykHInoBfRpRMuNJC5+q9PC,iv:jpOnrVVKml3+N41dgOb/i0p9/nh+X6nSz96jv0Ql3gM=,tag:vgB4xBl71xj1Com1qNLlig==,type:comment]
            #ENC[AES256_GCM,data:R3Zm7tzJRRfy/Od32gFRNX8yHFd0nPG1yFi/Ld+WE6w3Dgr3il3UTJY9iyfHnz28k9k+2w9uCJAV0gIFEtxelIzS8g==,iv:fhZ5pAomq+pVlrx+x6X4qMVCYvpoZaaIk2W3HkH6CuQ=,tag:hF/zonKi6iDAJq+6SMcX2Q==,type:comment]
            #ENC[AES256_GCM,data:OrT7YRaAhNQ2+QtrEjCLAl2pToL00sUKiud39NUjzgJCAFO7x72vmH2C/Bq++7g58KQP8hMIEfetvJpe5fk=,iv:hRlSEeS82bj7HueVH+cMODWzk2z3/1eTQKT5U9/qHog=,tag:8CkqWksRqiq6rMtJjnwptw==,type:comment]
            #ENC[AES256_GCM,data:FV6PnZE9ZvUDjHSgUnjS4naG4J0snPyJU+v5B0OrdTNkIY4PCNuG7fc+E+oG+QCCso1UyNgGwQYr,iv:FSp1sY+n0QeIe1rEp17BBT8tWkC6uFkrgOGVMvNubJ0=,tag:d9sVAqR0XiBwB5ThsPl6tg==,type:comment]
            #
            #ENC[AES256_GCM,data:5+ihmQelijGk4Lm6SrJPfSoorQMDheiWid18vqDh+YrkYcsgR2LK6Oezc9q6rO5w1P6JEFc0gKD4LSpntQam0tQ=,iv:/oTB1Hxv5FhFw8jofuTdkJCFRrpNqmwsC0xMo/5zzrU=,tag:ul3KCvsVoNYRneotFWZa8g==,type:comment]
            #ENC[AES256_GCM,data:7b6smcKOqbPv8IIlhZBhkzUh/J7NQoSgw0+/duAEuhiluLw/yePIbDzA5chGbmPnxwCgmZntQ9pAqKi1qg==,iv:e4H0xUkpKKy1P5FBsIkmzGxdLnTLM+oNwuV6ESWhLJA=,tag:SHAwxj7zeNnN8vo6VyobRg==,type:comment]
            #ENC[AES256_GCM,data:latW7V+plqXUdaOimYrWN6eV1T/P,iv:FTE9pH9PGa7yFEQD9c0f72GroYjNuaL4Rnhb2iy/kGM=,tag:qhHsxzsU0VEPNQBK78ZjNQ==,type:comment]
            config.yml: ENC[AES256_GCM,data:254OHuaY5A6RfjCsv9kln+SLxxa4w/E5bC2fhCHJatsL3nzmkBD35uBrbKlqiHsYtpLt1+H7rhy55NdnojwJrtZx4z9NC4fDs74c2B3nsH9kdfAYq2BCbvBoqOoUTDnH+TKw0VuMWr2x6gPoiQNbf//f+sk/fISB35F0mbhodUEIVXwbJbYx2iafgVZio5mkvYHnCcT42d2UZpaR38jNlEuwfHGs2+wjA24iTyzZkM1zGNfqsjGge5u5P+A5OSg83GSPJUsJHnn72fMVWrKzoVT3XkAnYW2dYqceD+B5aGbqW8D9nB91DbaqJ8yedStMG0k5pemsNErn8UdwXdu/y5EqOYELkfDWJJ2Qn8LbC0T5j89m/5dL3tvS/upI2K/gWLoJomK9RCkNHFd6p3RsdbS1eUFM7+J0vIOGl+MezTk3lhDdmJsiV9kfFHBBE8VK2Bhu+o0L0+cNtRXi6KtQSmfCZDE24aUMGGgw1cjolGxsWlLLD+BWEJ0Kb55Oz/rvjrsZ6JcxNHstUeMQV3hpZH7XhQnMMGPfRmoCdCWRxx7ogQ2w4cs0gpvP1cqf5Pj+RX1kBAHSSAeFew9GR72RNb/eEzrsKXiYLu4MvDmeIftsk/oNErmYyOxBTyoQ7g==,iv:F95O6Nu/wA0c0k3PUjxP+QanwchQXc5ANgOKXcU/26M=,tag:zwTi2M2oIPRagE/t2rFg0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aFZleXFwT2hKelRIV1B6
            cyt2UGtyWjJ1aGV6RmpQbUQyWHRUaW5ObVdzCnNmSTQzNFpuYjlYdkZiTDZEZWRP
            bFgxUlUxaEhYeGpvUHhUVTd4UjJTUGcKLS0tIFFpMHV0UmllNlJEZnFjdy9obVQ3
            c21oSzJoaHhCMmZVMnVKamhGU25RS28KoQOHQpPBcFowFItRDrbfM89SD9ENnQlg
            fteIT3kvChZM46k3sWCYKnWdyS/M3LAiZSnAyq5jWMaWf2RaV1HPbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T17:38:36Z"
    mac: ENC[AES256_GCM,data:Ru21LNvlPXRF6ZS0AXTRJZtrs+B44QPQfklJCaNUYixpoQfHEqmXkVy3U7sWg7/A/n2X/QHUJ62yoiVMgQQYPPZu0nLzWaoqsA08VsR2PMUmS/XPhpr2E4Lu7QpmWH5BJER3OowTnFk4UddwS+atSokmr7TcniNv5ebxxUClNvE=,iv:aUvbyFzvcbxTf7cH2xJxYbUT4Gp+PTLt394rjd7gu0o=,tag:Y4QgudSj1ag5ObhW2dwD5A==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.0
