apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: samba-config
    namespace: samba
spec:
    secretTemplates:
        - name: samba-config
          stringData:
            #ENC[AES256_GCM,data:PSSv8nN+GAlrHwAWioPv+bSUUdwZGuRDL79otS/T4WNKy0d1ikhkrMYespCCBUvHmNG/iBTW70KfxEDPoqzBMNA=,iv:49UJl6A0uz0Mb9Z17ITuTbQw/NADPZlNAt82JGQVC9M=,tag:beq2Z9wlQtPE2l1bZ8nCUA==,type:comment]
            #ENC[AES256_GCM,data:OW9uclCnoxIovXcdQIHiG0l15loltNihNlm6RAb1mMMosjrAH1JtTTdDuzV+0sHsTO7o39AYEFf9xBfsPw66,iv:5/fU7iR9XmPIaSp163JcunvpxHmh/+sqF2IuMH+ZCVY=,tag:qndppoUhp8OkiUlZNF4cRQ==,type:comment]
            #ENC[AES256_GCM,data:esR03YpNVkeoRFs28g+zLGsYA6diC9/kG5/kXfXM0OWbIipBfXM+jZryXrPiUztdisjIIcgVQiAUFJe4s9qrghfl7A==,iv:2ZSEtItetFsvG+Im5UatmGwn4DZegpqjd3a9F1mh9UE=,tag:jFJ5Zydi9eTEDMZD7ouWbg==,type:comment]
            #ENC[AES256_GCM,data:O7boIEXa2TPNeg/LwGf0U1pVu9lfk09DSgxC58IlMqBrdGZS4XvEDM+tFLEGdyqEIhiNZZmiixYN1TG8Qx4=,iv:4h7U3AhUhd7bAzWWxSZFbNc8Z74AmGw8u8XzOEWQTyE=,tag:J+5ZhPRIOHsUgKG/c51euw==,type:comment]
            #ENC[AES256_GCM,data:jVbliC7vQWvo6x3W6wFOD438uepFtv9q4Hht/36dAeI3bR9UOpaRXFqpGLmLWJCqs48+4Sz13cAg,iv:l9THPJyYqxiE4nhJRd8YzKxMI79smR/ADJe0Zq8qzM0=,tag:bylEEu/4WYygSviDQWAPQw==,type:comment]
            #
            #ENC[AES256_GCM,data:duIureHlWX1D7L7rlWfs5DEKlZHF/M0+tu2WNoChN0+9+3MOsSVZs9iarCEi2cl0z4Xv7yYI/Rk6UzXlj0md8KU=,iv:wAGpz6zAOiJpnuUb2mWJi9o9LuICcyiojQ7OclUm5W8=,tag:2xhPlGGDJoVaqOg2/emoiw==,type:comment]
            #ENC[AES256_GCM,data:yAqeIgiW+941QGrNvCXG0FILKL6f84DIIb8HmRPYh1IfybfHiWY7Vq5ZsvdHk0VitqLnkbJAFs5Az792qg==,iv:5NB30usUavVtr+foER9z/qcypwP9ACggR7jt2+63kxk=,tag:gFo/tVv60tszMRSmM8hzpg==,type:comment]
            #ENC[AES256_GCM,data:TMiQ7NM9wBLqwpFn7yg3OYhuJbpZ,iv:VkX2z7WubELLlb6v/aEfjtt1w3KZ7JAb4NgmlgIA07c=,tag:Gvpc6hUEfhxzZmzMtUQsYQ==,type:comment]
            config.yml: ENC[AES256_GCM,data:nt5aVzWfl/NZfWDhFnTVIAlyfDE33csrJfYiqBZPQGuVYutQSRgiUeswf9GNg+G19kKySXOy8Y6Y4BbddgTa7lTIUx1/pfwJZEPuheicgnzfjL1Ihqnv8VRPQsFRomgbHtV/Xo/xcBjiY9JLWoqHtdUSrfo78z4EUpjkso9Mmunvxot3t5Qi6nJY67uajIomIu6l7sT1b9dRaOHfLVRZh+Zs+runHH7vp8J3T0zOuH0FKzKRE4UV2I68JPpE31qa7jiiiLK3uVVRHPlexmmGMsi/TKddkC783DhskhgekGdp5OOyDyUsi9d6ujTjHkYRbekX1j6+TiW03QkBTNgEj1RAC6SUXvgctzAhYSqS8YGCJnDAju7djOJCp42bt7Nh9VCU/Hz1NP0I3NndJYieYeOPlyGJtdM7qZWtDW6EN6kwPikwgZ5yS2Zc77AItsrrWuHxMV+m1sKjGS35B0l1xjbg/Bc/mVsUrIHJYQUtf1jOffyKgE3ADVOvOqP87a6C6oJMTntZIfgixS2Q7hAnMoeyYYSJpO40hJezSui5a7H+VJmD6TDooftQdjjo92fv9GWOYlxMS7QNFm9/p5vOuirxloGhbOBXSH1ZDUkCr+paUA==,iv:0Mv656XD0DNpXtX3/zK5U8Q9ZP1+fCgSvvT48Oj5RvU=,tag:o6e56oLcWXe3v7VZpqHhLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNGhleGE5MWdhaW4wNUp2
            ZU1xcUhCQTdIcmpkczVYdVl2d3A4ekV4VG5zCmlwODNFQzRyMmFsUXg1OFFpV0Qv
            cW1teUl4Vm83NFBwVGl1cmppSVRVUVUKLS0tIGRtVEwrTHdOZFc2dnVheThXQWU4
            anl3RlB5ME5zZm5ITDYxU1AxVDdXdFUKEln66dufQDn2Qzc21yDYDj01usmrEEwI
            5AZUM4qXN6m6sAqGQVnwqJKk6oA6mUFAjwfMUYT70S3c/wDuIVWd0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T20:20:34Z"
    mac: ENC[AES256_GCM,data:kJXUtFapvz5VkvfKuzAcuZgI8cjhtr1VVdWIYOMEsFc18Rt+Kal6q1wGkpw2zNPIS/biGc6MoCx2ygmWF5njGLWggK352xtZ/wJPoIwCNda882Zr2s2fCcQybr5PXsdJ5+naqQA+w05+a6izhaqmpQPfDhXaVp9gDSuTnwdHoIA=,iv:Djo/UXnTmFttYiZLWFzth8j8gaghrxlbu33czs6LgEE=,tag:5JAqHFjp9mylQI4Rzurulw==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.0
