apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: syncthing-oauth2-cookie
    namespace: syncthing
spec:
    secretTemplates:
        - name: syncthing-oauth2-cookie
          stringData:
            cookie-secret: ENC[AES256_GCM,data:3E2d7p2Ydh7D3KkEYqL450iI+4oiPmkxzMvWHaxD/kvl7RPo2BQc0S5z3W8=,iv:VFE7Pig17HPpupeCOrQ7kZA1i3BqW1Z1AdXUjyeubBY=,tag:jFDCXuayulfYvEQoOiUf+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsKzRxc0R6dGFTVUV3VjFm
            RVhadjd6VUU2NWJsQnFVN3kzRzY0elo3SHpRClVSL2x0QlhFMVhnNGovN244U0lK
            Z2ZPWnhyZFBlTUVNZS9NZGo3YjUwMG8KLS0tIGwrWGZDUllIZ2R0KzYrU3FrWmpD
            ajVJVW1rZ2dRL29VVjZuY3k1ekhvdlUKI58rIS46zR0JLQBqVx8JSgv/MV9umIZY
            dqvJ/KQmRvqQJcMgrT19wH89zWLWNbpTfmzRa6bXEcShefF3cfnjHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T09:15:55Z"
    mac: ENC[AES256_GCM,data:luAxSNTSgohQxpfo8+AA1/reCMtTxw3LwTnTkYR+ovm6+Zr1RkELCPvahTpBWJugTB6zhJzcLWJhXw8E0Bbf6aIxkMZshk2gt1YqLggEuV7mj3lD1oHLHgqbv+ZJeIpcu1ZZh27gkYaHQcSEQExZ1axDG2QBsbViUJEL+oH41RY=,iv:pLVz3C/somV5D6+J204eI2NfwPw2O+wgp7nlN/f4Vx4=,tag:5sN2RdzL17ThDHvs5PhNkg==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
