apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: vaultwarden-admin-token
    namespace: vaultwarden
spec:
    secretTemplates:
        - name: vaultwarden-admin-token
          stringData:
            #ENC[AES256_GCM,data:K10olQ03dlL8EuoQs7xvj/A/6OR780cOOJg6Jqi1DCnqq2JDLgqRCEfjVFZzqMW7o5hFAhsbNqdUlFmajASRlofiz2zNrA==,iv:NuHxpvWdCu62bQFlgTkTsuU1geJcZGRKMSASvytJrAw=,tag:oQTPgD2ppTKJTvoIXeSllg==,type:comment]
            #ENC[AES256_GCM,data:hUD4IhI4MDg3oFI8nXx9sch+XgcmNLRcPxr/h/m1w0oX8jvJQVMjMAybrJ0tmrS1uo+GJI3S7ssI4Z5GMInfb10=,iv:SA/+t71Ed2tVO50x57zp7IfZwX0zjimmPY2BiahJsz0=,tag:vMsiCghgNlBqpKcVOKhYsw==,type:comment]
            #ENC[AES256_GCM,data:8PM8OzvP85ivFFk4n9nyiHDRG96QiDZ0MeNEL6LbvD5mxKC5xRdTqzm85ky7l5/WhJA3aYnCuNXPxw==,iv:ETRXrjMbk+k1mu+jaWUCoO504VBiDusLEQe2GtO+Qvc=,tag:rcPueMBSlR1zUI2H1H6HJg==,type:comment]
            #ENC[AES256_GCM,data:xpV7cprCBn3BKw2zmMgJTD/ezvOalAzLDqVBrbZhvqtdv6XNj+PJU4g47uBolUJZkBt5SJg7wFdsFlt4SImc5GR7dx704g==,iv:OEXy1z4BoG/SK0kgm5I4cvQECkPx6f/CHrYVR/aiDzU=,tag:Mu24HAvuxEPjOfKoqk84LA==,type:comment]
            #ENC[AES256_GCM,data:6julGq0EmWiiuf5eY7Co0x94cubJfMGzJyA/LBc4HiiM+aA7pw7RY75UuK5dT+JpqKlzPf0yspN1s0Ww2jCCTYK9dO8bA8U7,iv:Uv1HVv1gI84J/Dx2QNDZwKoqmOGGZqWRkKw3sbuudVw=,tag:+WkVMDkWrd1MxC4WqEPVWQ==,type:comment]
            #ENC[AES256_GCM,data:UURVnvM2m5RJEwPvYf0G6MTjknDXxU99CZYb5FCzN5cwJ884WjE=,iv:4i6Yjb/e9pPQ+b2S8ygkXLAlf2vKSEGoqc47UFw0QIY=,tag:spTAA/dTJzEG1JdtfNeEgA==,type:comment]
            ADMIN_TOKEN: ENC[AES256_GCM,data:SgRLEth6VMZ3uKQihkIRFXixIN3mEMSqXE+5u+FF3GoEiuAgWPqhLH67ATyyflqK5Ez3KUHiY/OEDYgirDfcy74DxjhqOysXgE70w0LsjHQArwfvsqaKOf6zmWLabkgubpaeg9HvjUzf+ihaM09Dg0gjYFItrtO+BG4UYuVo/1dsW5VLb5s=,iv:yRmmwCIdJxPibksqPCaXdcSjWxWDPRuQNAeXXHvPqLs=,tag:VBKvfYI0bhwt14CBrYY1Pw==,type:str]
            #ENC[AES256_GCM,data:t5LDE80eVzNNYtqYtTIb9xpvrMz0ciD3pdYj07SCT+1uREYi9Xcdf2Nmq1Jg0QR4+HgSnmZdFJegvbRB7qKtkpRYxA==,iv:dlwo1Wt4Eg1dWutvnyHsuiy7HdbzbE7Sg4uca8AQFns=,tag:IvMypyvRDuHh50Vgoa+tHA==,type:comment]
            #ENC[AES256_GCM,data:dUe8QcTBI4+U/2p391ggMrGhOdli4U7QOVfkCozJR2ukJ+j2g7aHHK97f4SgzSJ07L7cs2mNmN54fWSPcSHifCgD,iv:MlF210tgVLzCYRJXBXdeyqi+I0pA9OUc4Wy13hy9qZI=,tag:YZfPPpAzmoQKbGU+5iuuqA==,type:comment]
            #ENC[AES256_GCM,data:Alb0dbe3dU9NnQ3hCQk+bEe3J6DNwrV7welDbKX6VonRcOaKYyuxifJ0uLNg/CzsedSSKVHI6CfC914UeMjPOHyj,iv:ZWwLyoFZSSLVSCtOQYJK3GyM1IlIDR3uxHbK8I/rRko=,tag:5fRc9W1ny6M2rZ6+7jnJ0w==,type:comment]
            #ENC[AES256_GCM,data:8zCeaI1PNqu/wRUzUwcziwCv9PyIhydZP4EkTg==,iv:yqP1tYfl/FJzVeaqymgzFxX/H6bIrUDV2/wxIltFm5E=,tag:S5BPTWG3GMymcj1waSG1dQ==,type:comment]
            ADMIN_TOKEN_PLAINTEXT: ENC[AES256_GCM,data:JaC/K9bnZESxmEQkcmF4BvVk4ZX2JnfifmaVW8wPSzecQ5Fr2ybkdrRML4atZ8VzU4B3egThhnEj1J8J290=,iv:dIXxR7YZLADCwtbX5sMKFO+JIp/jjwonvecjDDV09yA=,tag:uq76OuxsKSS4r+sYttfUtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVUdOTkxMa0NzVjFJU0lZ
            TmZBdFlhMERTaVdCNGxWRlhVTlJJNHdvbWw0CnVUckVObmovdEs5MDBNRzN6REVj
            RHZXMkM4MjdxdmZnVFh5UHRzQTNzbFkKLS0tIDVnWlVvcmV2dWFyQ0V2dDlJcHpU
            aUxwdDJBSjkwOWZDRnkzZjlTcTZSbmMKM6LeSu5FtOIlqoS0LI2AnOOn165gq3wb
            4taE/y7H+eq3WmymN2OJU5EuZIffX+9xPcvEjUJdw82bhNiblWUNpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T09:17:45Z"
    mac: ENC[AES256_GCM,data:s51dDYSD8+wjinmtXuy/ZSRfg1TwQ8mMoFfzPEZ930p9vgFAc0DzEPzTqc4qvrNU7ZqRA/srCDWJt+2lshiREf6berl0nQmyOEFDy6ZlEliAGwVtEHhIZyI9Ant6kkhbDcZDLP/oj3v5lfbi0f+lhgohP/ieBkH/xC6uzjYI8LA=,iv:SnTbaJgm/ti/lXRyMoAKnE5QMCbQgPhxu8/r/kEDK6U=,tag:Nbof05JSaj7YfUDMNeDMhw==,type:str]
    pgp: []
    encrypted_regex: ^stringData$
    version: 3.9.0
