apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mullvad-wireguard
    namespace: qbittorrent
spec:
    secretTemplates:
        - name: mullvad-wireguard
          stringData:
            #ENC[AES256_GCM,data:QkGAdaUofaMCd4JQaAZVjrha91GBR6Do2Gb0oCjbA+ZOggBqJnKFzFq9nlxDuD3ueiuKu0wbJzuW/dnYAsw=,iv:tCiNlPktvrb3Ium8nh9o37IEiVJjvCF/u3FYynIfDOs=,tag:srV9Yjm34sMS8cVwEZ50hg==,type:comment]
            #ENC[AES256_GCM,data:vUSuCe1Uk12T8Bx2EgQzHGB0kFQySP4pp2zWpJLZo33dAab9ABXUrjFifTv3eMcJzOa+LCClgptB2fM+ATk=,iv:7dJhfUJs5B+40FIHp04+QWyh7YJmJ+zA7oSv5BQDfB4=,tag:GXMxxczWpDvki2Oi/bBD7w==,type:comment]
            #ENC[AES256_GCM,data:n3MBwQxoH4hfnhvRTC49aeI39ZRczcWNAvsSDoIDD8HXbKedF24Jgw/oijJ+a2q8L6aDwAyOu6NL,iv:CyZelMSfsh0PAng/R4jcrahU0H28vO9RfoCnWomhErc=,tag:xUSrVq/qzvKIxTejE0pWRw==,type:comment]
            #
            #ENC[AES256_GCM,data:OkJKwXEXxE+AAuXNjtotKOAECBj8IRh5nB5Qn5c225YJQLOKIqiuFfsZwGKftBH32ClXAeXhsyjCZfVhHlhByKR0mf0Eu4XjNg==,iv:3wn8YQau3gSt6J4v4UDjj5x0KuizdCwuY6sjjRIUm98=,tag:IvzVFhxcatz6YX517MDxbg==,type:comment]
            #ENC[AES256_GCM,data:hSwsdl3B+RYNB1tk1J2V4uNHNrn5alllq4p4Ew689QggSjqmCI5JhDIxfoxyyClo8KRkd3q+ejABcW8VzvxcOQ==,iv:2C9N9uL4z4TifN0rREWc+N0c3HxDoRfk4bVDyL2BDxM=,tag:Xbv854CZCuAK7tEJEJnP8A==,type:comment]
            #ENC[AES256_GCM,data:qVWKJsmD8kakdlYOx98Awxlwy9tjd5HWKxfUsfimw1Sp8F6egc6G/sIE+vOSoXSMqgDLLs7LgTb2OorBJg==,iv:n9EoTATJurK6ZKga9NxbEGLp16H7HAe+IKVhjlVaZi0=,tag:xZX4D9n3KnaGc8pxDdu2sQ==,type:comment]
            WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:/Mj+NCrDEf/KdRKFC4UBaB9NtKIxLvZrA4L2MnuUMTf9WxXls5E2MJH9kQM=,iv:uYbn73y0LdrWINn0qXK8IhNP5MCEsXWJMpJtq6RymRA=,tag:wuvwJF1AxnVh8hU4l/gPHw==,type:str]
            WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:SrklvX2FvO6yu2ch3FAvzLYdygZbPZwmaYY2S5uRRS1rlZihyblLYIbHKrGpu9D+,iv:l5xsk99p7fskrrPbg31mFuvUhFBiQjOM5sGaPx4mPdY=,tag:AgZI4x9rrDb+DmL3pdjR+A==,type:str]
            WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:T0lZrXRsFpISuJ9KRo8H0x5IEApUn3HFlc76sM2hVxz9xXZ0XrSizow9SqM=,iv:ULhCKrJgjIwgUiZelTNMpV01ask3Iq6tRWNMjL9kfus=,tag:Vk9DckyrgsYnuE7RDvguQg==,type:str]
            WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:BqKv+Svuunq8ew941w==,iv:DUhYDbiJlVeCRayI2DX1Ud9PFUB2V+L1qThILJJ5uHE=,tag:g2sktdSXFx+spyP0HxQRvQ==,type:str]
            WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:Z0ZEXM0=,iv:xHpr4DK1Qdsr17IXxzimthumdjFbZNsRqzeklOgvRn0=,tag:IEn6IN6k2qJzC8MNaTXM8g==,type:str]
            WIREGUARD_PRESHARED_KEY: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sjrw9cudya5fhnucvlhqsrfpv8g6zn56tvffx3ns5rr935z3v3aq7hydlz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UGovd0RhWUJsaE1GVkI1
            WmxOVzRZa1VOeEU0Y3BRak91U29NeDh6UldvCkVPNEtlRHkreDhJNkNGQzRqK2Fz
            T0QreW9QQTVjaVJFeGNQQ1VVMmpoTzgKLS0tIDFwZU9qNzcxZnNKRitwRy9CY0Yz
            b1ZhMTQ5UEZmazUzVktwdkZBUWwyMTAKD7JSlAG0Z35iFrMaMLWrY7EkkW0VjTEu
            FnQYw/JlRUFJkqCES089pdOwvV4TJ6mQ6CQAHam1jElxJZbt9dDoDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T19:55:55Z"
    mac: ENC[AES256_GCM,data:IYxbCb57q15oxejTcxFGH9/pvfS3pKpm83vOoQgs8jZ3Er0HunghHTNEKLPnaU7KY9ofP5lbCVG/2vPPNajYLCGcTZDzH2y4gCrMCJaH3Oz/wF3BUrgDYZJCVvyigNWfeA6p2M2J0eeHEZK0XNYPwP9Vg4QJuuh/YEMxiOP0TOU=,iv:3j1E/vU7g4PJhw4qp2KLbmTwHd4mtdkQFU2iiolFN9A=,tag:dmZZbcb90ee1ZWp052wLAw==,type:str]
    pgp: []
    encrypted_regex: ^stringData
    version: 3.9.0
