owner: infra
enabled: false
components:
  - name: kadalu
    namespace: kadalu
    chart:
      repo: https://arch-err.github.io/charts
      name: kadalu
      version: 1.3.0
    syncWave: "1"
    valuesFile: values.yaml
extras:
  kadalu: false
