owner: apps
enabled: true
components:
  - name: cyberchef
    namespace: cyberchef
    chart:
      repo: https://bjw-s-labs.github.io/helm-charts
      name: app-template
      version: 4.6.2
    route:
      hostname: cyberchef.3rr.dev
      gateway: public
      service: cyberchef
      port: 80
      dashboard: false
    valuesFile: values.yaml
