# Kadalu namespace with privileged PodSecurity
apiVersion: v1
kind: Namespace
metadata:
  name: kadalu
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
