{{- range .Values.components }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Git repo for values files
    - repoURL: https://github.com/{{ $.Values.sourceRepo }}.git
      targetRevision: {{ $.Values.sourceRepoBranch }}
      ref: repo

    # Helm chart
    - repoURL: {{ .chart.url }}
      targetRevision: {{ .chart.version }}
      chart: {{ .chart.name }}
      helm:
        valueFiles:
          {{- if .values }}
          - $repo/values/{{ .name }}.yaml
          {{- end }}
          {{- if .secrets }}
          - secrets+age-import:///helm-secrets-private-keys/age.agekey?$repo/secrets/{{ .name }}.yaml
          {{- end }}
        {{- if .extraArgs }}
        parameters:
          {{- range .extraArgs }}
          {{- $parts := splitList "=" (trimPrefix "--set " .) }}
          - name: {{ index $parts 0 }}
            value: {{ index $parts 1 | quote }}
          {{- end }}
        {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
